### ISSUE TITLE
Using the libraries in own projects

### ISSUE THREAD

**Issue by piperoc** [alibaba/yalantinglibs#129]
I am trying to use this project in my own, but it's not clear to me how to add the libraries in my own cmake structure.

I'm using CMake 3.16+ so adding the directive 
`target_link_libraries(${PROJECT_NAME} PRIVATE libcoro_rpc)`
to my cmakelists should handle all dependencies automatically

I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no answers.

### Reproduction way

The best I could think of was to add the entire `yalangtinglibs` into my own directories.
My file system would look something like 
.
└── my-example/
    ├── my-example-lib/
    │   ├── src/
    │   │   ├── main.cpp
    │   │   └── ...
    │   ├── include/
    │   │   ├── include.hpp
    │   │   └── ...
    │   ├── third-party/
    │   │   └── yalantinglibs/
    │   │       └── ...
    │   └── **CMakeLists.txt** [see detail below]
    └── my-example-test-app/
        ├── ...
        └── CMakeLists.txt

The highlighted `CMakeLists.txt` looks like:

```cmake
cmake_minimum_required(VERSION 3.16)

project(my-example-lib
	VERSION 1.0
	DESCRIPTION "EdgeXConnect RPC Core Support library"
)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_library(${PROJECT_NAME} STATIC 
    src/main.cpp
)
target_include_directories( ${PROJECT_NAME}
    PUBLIC ${PROJECT_SOURCE_DIR}/include
)

target_link_libraries(${PROJECT_NAME} PRIVATE libcoro_rpc)
```

### What happened + What you expected to happen
The code cannot build as it cannot find the `libcoro_rpc` includes etc.
In your example it seems like I would not need to add any more `target_include_directories` or `target_link_directory` instructions.
I'm a bit confused.

### Anything else
It would help to add some library install/usage instruction in the "getting started". I can offer to write it up once I resolve this issue

### Are you willing to submit a PR?

- Yes I am willing to submit a PR!

**Comment by sunflower-knight** [comment]
I think "add_subdirectory" for thirdpary/yalantinglib will be a better. 
when you use  "add_subdirectory" for yalanting , yalanting's cmake target can be used for your own project.

**Comment by sunflower-knight** [comment]
There is a real need to clean up the code architecture and make it easier to understand and use. Thanks  for your 
issue.

**Comment by qicosmos** [comment]
I think the example can also help you:https://github.com/alibaba/yalantinglibs/blob/main/src/coro_rpc/examples/helloworld/CMakeLists.txt

**Comment by piperoc** [comment]
@qicosmos  thank you. As I said in my first comment, the example did not help me much.

What I ended up doing was to reorganize my code so that my application would be defined under the /examples directory.

Now it looks like this:

yalangtinglibs 
├── cmake
├── include
├── src
│   ├── coro_rpc
│   │   ├── benchmark
│   │   │   ├── api
│   │   │   ├── client
│   │   │   └── server
│   │   ├── doc
│   │   │   └── images
│   │   ├── examples
│   │   │   ├── **_my_application_**
│   │   │   ├── file_transfer
│   │   │   └── helloworld
│   │   └── tests
│   │       └── openssl_files
│   ├── struct_json
│   └── struct_pack
├── thirdparty
└── website

This way it builds successfully. 

I would prefer to have the ability to build your libraries separately (and maybe make install them), like other projects do. But for trying it out, I can live with this workaround.

Thanks everyone for the quick suggestions.

**Comment by qicosmos** [comment]
Actuually yalantinglibs is header only, so you just need to include the headers, just like using asio standalone.
In other word, you don't need use it in current directory, just like other header only libraries, you can put it everywhere as your wish, if you can't do that please tell us, we will improve it.

**Comment by sunflower-knight** [comment]
I will add the function for cmake users who want to use yalanting like other project. 
May be  ‘install’ all the head files in the prefix you indicate is a good way.

**Comment by piperoc** [comment]
@qicosmos @sunflower-knight  thank you for all your advice.

I put yalantinglibs  as a submodule into my project, and still having a hard time. I'm not using the conan package manager, so the following `dependency.cmake` will fail:

#the thread library of the system.
find_package(Threads REQUIRED)

```cmake
# 3rd-party package load
option(USE_CONAN "Use conan package manager" OFF)
if(USE_CONAN)
    message(STATUS "Use conan package manager")
    find_package(asio REQUIRED)
    find_package(spdlog REQUIRED)
else()
    add_subdirectory(${CMAKE_SOURCE_DIR}/thirdparty)
endif()
```
because as a submodules the `${CMAKE_SOURCE_DIR}/thirdparty` . If I fix that, things start building, but then it can't find the `asio` headers.

Lot of headbanging, but I'm ok with it -- learning a lot.

**Comment by PikachuHyA** [comment]
I will fix the path broken when yalantinglibs as submodule

**Comment by PikachuHyA** [comment]
@piperoc I fixed the error and write a simple demo: https://github.com/PikachuHyA/yalantinglibs_as_submodule_demo

**Comment by PikachuHyA** [comment]
hi, @piperoc 
Thanks for your contribution.
I have updated the document according to your suggestion.

https://alibaba.github.io/yalantinglibs/guide/how-to-use-as-git-submodule.html
