### ISSUE TITLE
Forward<->backward compatibility?

### ISSUE THREAD

**Issue by danielaxis** [alibaba/yalantinglibs#143]
### Search before asking

- [X] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen

According to this page... "the two classes can be safely converted to each other", i.e. compatibility should work both ways.

[intro](https://alibaba.github.io/yalantinglibs/guide/struct-pack-intro.html#forward-backward-compatibility)

struct Person1
{
    int64_t id;
    std::string name;
    int age;
    double salary;
};

struct Person2
{
    int64_t id;
    std::string name;
    int age;
    double salary;
    struct_pack::compatible<int32_t> z=10;
};

It works perfectly fine to
serialize Person2 & deserialize Person1

However the reverse doesn't seem to work.
serialize Person1 & deserialize Person2

I had expected it to use the default value in Person2 to fill the missing data but I get
**"errc::no_buffer_space"**

Anyway, many thanks for a fantastic library!

**Comment by qicosmos** [comment]
I think it's a bug, we will fix it soon.

**Comment by poor-circle** [comment]
Fixed by #126. We will soon merge it to main.

**Comment by danielaxis** [comment]
wow, epic support. Thanks! The new feature in #126 is also amazing!

**Comment by qicosmos** [comment]
The doc will be updated, now the compatible fields can be put anywhere in a struct, no restrictions anymore. @danielaxis

**Comment by danielaxis** [comment]
@qicosmos
Incredible, thanks for letting me know!
