### ISSUE TITLE
Deliver yalantinglibs via vcpkg

### ISSUE THREAD

**Issue by lichray** [alibaba/yalantinglibs#148]
### What happened + What you expected to happen

```csh
> vcpkg install yalantinglibs

yalantinglibs provides CMake targets:
    # this is heuristically generated, and may not be correct
    find_package(yalantinglibs CONFIG REQUIRED)
    target_link_libraries(main PRIVATE yalantinglibs::coro_rpc yalantinglibs::struct_json
 yalantinglibs::struct_pack yalantinglibs::struct_pb)
```

### Reproduction way
```csh
vcpkg install yalantinglibs
```

### Anything else
https://vcpkg.io/en/index.html

**Comment by helintongh** [comment]
In process by https://github.com/microsoft/vcpkg/pull/28984

**Comment by helintongh** [comment]
all ci succeed pr is https://github.com/microsoft/vcpkg/pull/29011

**Comment by PikachuHyA** [comment]
great

**Comment by yhyu13** [comment]
It seems vcpkg still cannot install yalantinlibs

**Comment by qicosmos** [comment]
> It seems vcpkg still cannot install yalantinlibs

Yes, it's in our plan, async_simple is the first one, and then cinatra, iguana, the last is ylt.
Need some time, but we have began to do it now.

**Comment by poor-circle** [comment]
Done.
