### ISSUE TITLE
some README.md errors

### ISSUE THREAD

**Issue by wuyingnan** [alibaba/yalantinglibs#149]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen
The link in README.md is no longer valid. Also, vedio should be video

`[Vedio](http://t.csdn.cn/uBRwn) on purecpp conference, start from 04:55:08 of the vedio record.`

### Reproduction way
Readme.md

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

I do not have access to the original url of this video clip.

**Comment by wuyingnan** [comment]
I found lots of talk and video URLs invalid now

**Comment by qicosmos** [comment]
Thanks, i will update the urls.
