### ISSUE TITLE
Could NOT find Threads errors fix

### ISSUE THREAD

**Issue by helintongh** [alibaba/yalantinglibs#156]
### What happened + What you expected to happen

```shell
mkdir build && cd build
cmake ..
```
this should generate Makefile,but in azure microsoft pipeline(or in minimize ubuntu 20.04) will report error.
error as fowllowing:
```
Call Stack (most recent call first):
  CMakeLists.txt:13 (include)


CMake Error at /mnt/vcpkg-ci/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Threads (missing: Threads_FOUND)
...
```

### Reproduction way

Perhaps the following statement should be added to CMakeLists.txt
```
set(CMAKE_THREAD_LIBS_INIT "-lpthread")
set(CMAKE_HAVE_THREADS_LIBRARY 1)
set(CMAKE_USE_WIN32_THREADS_INIT 0)
set(CMAKE_USE_PTHREADS_INIT 1)
set(THREADS_PREFER_PTHREAD_FLAG ON)
```

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by PikachuHyA** [comment]
maybe move `find_package(Threads REQUIRED)` in cmake/dependency.cmake to project-root folder is better.
