### ISSUE TITLE
Install and export targets

### ISSUE THREAD

**Issue by lichray** [alibaba/yalantinglibs#160]
### What happened + What you expected to happen

No CMake targets are available after installation.

I expect I can

```cmake
find_package(yalantinglibs 0.1 CONFIG)

add_executable(main)
target_link_libraries(main PRIVATE yalantinglibs::struct_json)
```

### Reproduction way

Write a `CMakeLists.txt`, `find_package(yalantinglibs CONFIG)`.

### Anything else

Here is an example that
1. exports targets,
2. writes and installs a `-config.cmake` file that contains exported targets under a namespace,
3. writes and installs a `-version.cmake` file that describes the compatibility policy.

https://github.com/zhihaoy/nontype_functional/blob/314c1ba4ecdd9ba9ed1ab4fc9246619f98eb08eb/CMakeLists.txt#L58-L73

In your case, the `NAMESPACE` should be `yalantinglibs::`.
The `project()` version should be set to `0.1.0`.
And the targets name should be renamed from `libstruct_json` to `struct_json` (The `lib` prefix is awkward; if one of the targets builds a shared library in the future, its default name will be `liblibstruct_json.so`).

**Comment by PikachuHyA** [comment]
Thanks for your advice.
I'll do the refactor later.

**Comment by PikachuHyA** [comment]
the cmake config has been updated.
