### ISSUE TITLE
rpc_execute.hpp 中 147, 275行的 connnect 这个拼写错误, 给改成 connection

### ISSUE THREAD

**Issue by QuantRokkie** [alibaba/yalantinglibs#168]
### Search before asking

- [ ] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by qicosmos** [comment]
Yes, thanks for your issue.

**Comment by poor-circle** [comment]
Fixed by #169
