### ISSUE TITLE
Securing the RPC communication

### ISSUE THREAD

**Issue by piperoc** [alibaba/yalantinglibs#179]
### Search before asking

- [X] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar requests.

### Securing/Encrypting the communication
I have a use case where the RPC client is on a different network node than the server. I don't know if there is any plan to authorize and/or encrypt the connection (like pki or similar).
Not a showstopper for me, but probably desirable eventually.

**Comment by qicosmos** [comment]
Actually coro_rpc has a;ready supported ssl, just need to call init_ssl, 3 steps:

1. enable ENABLE_SSL;
2. server call init_ssl_context(https://github.com/alibaba/yalantinglibs/blob/main/src/coro_rpc/tests/test_coro_rpc_client.cpp#L73)
3. client call init_ssl(https://github.com/alibaba/yalantinglibs/blob/main/src/coro_rpc/tests/test_coro_rpc_client.cpp#L50)

and then you will use ssl stream to communicate.
