### ISSUE TITLE
easylog使用疑问

### ISSUE THREAD

**Issue by sourcema** [alibaba/yalantinglibs#206]
您好，请问下easylog中std::vector<std::function<void(std::string_view)>> appenders_; 这个变量作用是什么，我看实现在写入的时候会遍历这个集合调用。

**Comment by qicosmos** [comment]
这个是为了扩展，现在默认情况会输出到文件和控制台，如果你希望这个日志输出到其它的地方，比如输出到UI界面，这时候调用add_appender就可以实现这个扩展了。默认情况下这个vector是空的，初始化添加appender才会有东西。

**Comment by sourcema** [comment]
ok, 谢谢。
