### ISSUE TITLE
Chinese document display error

### ISSUE THREAD

**Issue by luzhixing12345** [alibaba/yalantinglibs#214]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen

If I directly access the Chinese link mentioned in the project README: https://alibaba.github.io/yalantinglibs/zh/guide/coro-rpc-intro.html

There is a problem with the Chinese documentation page

![image](https://user-images.githubusercontent.com/56221493/219962247-f65cb123-ebbc-48ea-a3c7-f3f5eca5e5ad.png)

### Reproduction way

https://alibaba.github.io/yalantinglibs/zh/guide/coro-rpc-intro.html

### Anything else

Enter from the[ English interface](https://alibaba.github.io/yalantinglibs/guide/what-is-yalantinglibs.html) and switch to the Chinese display correctly

Maybe you could simply delete the Chinese entrance？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by qicosmos** [comment]
Yes, it's a known problem, but we are not familiar with web front end, hope some body can help to solve this problem.

**Comment by qicosmos** [comment]
There is a workaround way: change the language to English and then back to Chinese, the web page will recover normal.

**Comment by luzhixing12345** [comment]
ok, maybe I can help to fix this bug

**Comment by SoTosorrow** [comment]
it seemed because "**.VPSidebar**" is using _position:fixed_, and it use a fixed size of width in _@media_

**Comment by qicosmos** [comment]
Please try to fix it.

**Comment by SoTosorrow** [comment]
> Could you please try to fix it?

I can also try to fix it. But I think the web page code is inside the folder _zh/guide_ of the **website**, but you make them marked in .gitignore and i can not find where the error is.

**Comment by luzhixing12345** [comment]
have a try, I'm not familiar with vitepress and I'm reading the doc...

**Comment by SoTosorrow** [comment]
> > > Could you please try to fix it?
> > 
> > 
> > I can also try to fix it. But I think the web page code is inside the folder _zh/guide_ of the **website**, but you make them marked in .gitignore and i can not find where the error is.
> 
> https://github.com/alibaba/yalantinglibs/tree/doc/website

Sorry, i just saw the **website** but forget the **doc**, I'll try to fix it.
See who is faster (lol)

**Comment by SoTosorrow** [comment]
> > > Could you please try to fix it?
> > 
> > 
> > I can also try to fix it. But I think the web page code is inside the folder _zh/guide_ of the **website**, but you make them marked in .gitignore and i can not find where the error is.
> 
> https://github.com/alibaba/yalantinglibs/tree/doc/website

Get it, thx.
I'll try to fix it.

**Comment by PikachuHyA** [comment]
@SoTosorrow 
the website is built by vitepress
and you can build the website in your own computer

Before build the website, 
`git`, `yarn`, `node` are required.


- clone the repo

```
git clone https://github.com/alibaba/yalantinglibs.git
```

- checkout `doc` branch

```
cd yalantinglibs
git checkout doc
```

- clone `doxygen-awesome-css` (for Doxygen)

```
https://github.com/jothepro/doxygen-awesome-css.git
```

- install dependencies for vitepress 


```
yarn install
```

- generate website

```
bash gen_doc.sh
```

the script will copy all markdown files and images to website folder

then use `yarn docs:build` and `doxygen Doxyfile` generate html

**Comment by PikachuHyA** [comment]
the config of vitepress is `website/.vitepress/config.ts`
the config of doxygen is `Doxyfile` and `Doxyfile_cn`

**Comment by SoTosorrow** [comment]
> the config of vitepress is `website/.vitepress/config.ts` the config of doxygen is `Doxyfile` and `Doxyfile_cn`

Get it

**Comment by luzhixing12345** [comment]
Did you fix the bug? I think it might be a bug from vitepress...
Anyway it seems correct in my fork website: https://luzhixing12345.github.io/yalantinglibs/
and directly get https://luzhixing12345.github.io/yalantinglibs/zh/guide/coro-rpc-intro.html

**Comment by luzhixing12345** [comment]
By the way, I fix this bug by simply copying the correct html page, so if someone who generates the docs/ as [website build](https://github.com/alibaba/yalantinglibs/blob/main/website/README.md), the same bug will appear
I hope someone can solve this bug from the root

**Comment by SoTosorrow** [comment]
> Did you fix the bug? I think it might be a bug from vitepress... Anyway it seems correct in my fork website: https://luzhixing12345.github.io/yalantinglibs/ and directly get https://luzhixing12345.github.io/yalantinglibs/zh/guide/coro-rpc-intro.html

I haven't finished it yet. This is the first time I use doxygen and vitepress. I used to use vue/vanilla-js to write the web front page.
It's strange that Chinese and English are inconsistent in the sidebar, and it may be a bug

**Comment by SoTosorrow** [comment]
I just discovered the css problem. The label whose id is `VPContent` on the `zh/guide` page is missing the class `has-sidebar`. If you add it, you can fix the style problem.

such as `zh/guide/coro-rpc-intro.html`
![image](https://user-images.githubusercontent.com/50233205/220231164-2eefcc8a-67a2-4370-bbc7-0931c1d5e94b.png)

**Comment by SoTosorrow** [comment]
> I just discovered the css problem. The label whose id is `VPContent` on the `zh/guide` page is missing the class `has-sidebar`. If you add it, you can fix the style problem.
> 
> such as `zh/guide/coro-rpc-intro.html` ![image](https://user-images.githubusercontent.com/50233205/220231164-2eefcc8a-67a2-4370-bbc7-0931c1d5e94b.png)

@qicosmos @PikachuHyA @luzhixing12345 there is a simple way, i can provide a script (append on gen_doc.sh) to complete missing styles after generate html, It will not affect other files for now.

**Comment by PikachuHyA** [comment]
> there is a simple way, i can provide a script (append on gen_doc.sh) to complete missing styles

please submit PR and I will update the website after PR merged. thanks

**Comment by SoTosorrow** [comment]
> 

I completed a version first, traversing the html files under **docs/zh** and modifying the missing class. It runs normally locally. I will submit a PR later, you can take a look.

**Comment by SoTosorrow** [comment]
> > there is a simple way, i can provide a script (append on gen_doc.sh) to complete missing styles
> 
> please submit PR and I will update the website after PR merged. thanks

I completed a simple version first, traversing the html files under **docs/zh** and modifying the missing class. It runs normally locally. I will submit a PR later, you can take a look.

**Comment by qicosmos** [comment]
run failed on MacOS 13.1？

**Comment by PikachuHyA** [comment]
> run failed on MacOS 13.1？

https://unix.stackexchange.com/questions/663369/invalid-command-code-using-sed-to-replace-characters-inline

**Comment by qicosmos** [comment]
New problem: click the left menu item, the page not refresh!

**Comment by SoTosorrow** [comment]
> New problem: click the left menu item, the page not refresh!

This should be the original problem, I did not click to refresh before

**Comment by luzhixing12345** [comment]
> Did you fix the bug? I think it might be a bug from vitepress... Anyway it seems correct in my fork website: https://luzhixing12345.github.io/yalantinglibs/ and directly get https://luzhixing12345.github.io/yalantinglibs/zh/guide/coro-rpc-intro.html

Should I submit a PR as an interim version of the docs...?

**Comment by SoTosorrow** [comment]
> > Did you fix the bug? I think it might be a bug from vitepress... Anyway it seems correct in my fork website: https://luzhixing12345.github.io/yalantinglibs/ and directly get https://luzhixing12345.github.io/yalantinglibs/zh/guide/coro-rpc-intro.html
> 
> Should I submit a PR as an interim version of the docs...?

I still think it is a bug of vitepress, because it is normal to enter or jump from the en version, and the zh version has these problems,you copy the en html to replace the zh html and then no these bug. 
Theoretically, what is generated is consistent of zh and en

**Comment by luzhixing12345** [comment]
> > > 你修复了这个错误吗？我认为这可能是 vitepress 的一个错误......无论如何它在我的 fork 网站上似乎是正确的： https: [//luzhixing12345.github.io/yalantinglibs/](https://luzhixing12345.github.io/yalantinglibs/)并直接获取[https://luzhixing12345.github.io/yalantinglibs/zh/指南/coro-rpc-intro.html](https://luzhixing12345.github.io/yalantinglibs/zh/guide/coro-rpc-intro.html)
> > 
> > 
> > 我应该提交 PR 作为文档的临时版本......？
> 
> 我还是觉得是vitepress的bug，因为en版的进入或者跳转都是正常的，而zh版有这些问题，你复制en html替换zh html就没有这些bug了。 理论上生成的zh和en是一致的

Agree. There may be a bug in `docs:build`, and this issue should probably be handed over to vitepress

**Comment by luzhixing12345** [comment]
> > > Did you fix the bug? I think it might be a bug from vitepress... Anyway it seems correct in my fork website: https://luzhixing12345.github.io/yalantinglibs/ and directly get https://luzhixing12345.github.io/yalantinglibs/zh/guide/coro-rpc-intro.html
> > 
> > 
> > Should I submit a PR as an interim version of the docs...?
> 
> I still think it is a bug of vitepress, because it is normal to enter or jump from the en version, and the zh version has these problems,you copy the en html to replace the zh html and then no these bug. Theoretically, what is generated is consistent of zh and en

Agree. There may be a bug in `docs:build` and this issue should probably be handed over to vitepress.

**Comment by SoTosorrow** [comment]
> New problem: click the left menu item, the page not refresh!

I will try to solve it later, it may be the Chinese support problem of vitepress, I will try to modify the configuration of vitepress instead of using shell. In addition, does the problem of sed on mac need to be fixed?

**Comment by qicosmos** [comment]
> 

I think the problem on mac has been solved.
Please help to fix the current problem.

**Comment by PikachuHyA** [comment]
> Should I submit a PR as an interim version of the docs...?

@luzhixing12345 


> modify the configuration of vitepress

@SoTosorrow

feel free to submit PR to `docs` branch

**Comment by SoTosorrow** [comment]
> > 
> 
> I think the problem on mac has been solved. Please help to fix the current problem.

I tried to upgrade the version of viteepress and modified the config.ts, and the problem of style and refresh did not reappear in my local. I will submit the pr after I confirm the configuration is correct.

**Comment by PikachuHyA** [comment]
> I tried to modified the config.ts, and the problem of style and refresh did not reappear in my local.

run on local with `yarn docs:dev` has no such problem
however, when I deploy the release version with `yarn docs:build`, the problem occurred.
weird

**Comment by SoTosorrow** [comment]
> > I tried to modified the config.ts, and the problem of style and refresh did not reappear in my local.
> 
> run on local with `yarn docs:dev` has no such problem however, when I deploy the release version with `yarn docs:build`, the problem occurred. weird

I did not use `yarn docs:build`, but directly `./gen_sh.sh` and take the generate docs. mayebe you can just forget the yarn build?

**Comment by SoTosorrow** [comment]
> > I tried to modified the config.ts, and the problem of style and refresh did not reappear in my local.
> 
> run on local with `yarn docs:dev` has no such problem however, when I deploy the release version with `yarn docs:build`, the problem occurred. weird

I never using `yarn docs:build` alone, I just directly run `./gen_doc.sh` (it is already include the yarn build), 
I put my generate file to my server 
there is the link [http://175.27.159.125:9000/docs/zh/guide/struct-pack-intro.html](http://175.27.159.125:9000/docs/zh/guide/struct-pack-intro.html)

**Comment by SoTosorrow** [comment]
> > I tried to modified the config.ts, and the problem of style and refresh did not reappear in my local.
> 
> run on local with `yarn docs:dev` has no such problem however, when I deploy the release version with `yarn docs:build`, the problem occurred. weird

Did you run `yarn docs:build/dev` again after `bash ./gen_doc.sh`?

**Comment by PikachuHyA** [comment]
can you deploy the website to GitHub Page?
https://pages.github.com/

then we can test the website by https://SoTosorrow.github.io/yalantinglibs/

**Comment by SoTosorrow** [comment]
> can you deploy the website to GitHub Page? https://pages.github.com/
> 
> then we can test the website by https://SoTosorrow.github.io/yalantinglibs/

Done, you can check it.

**Comment by PikachuHyA** [comment]
> Done, you can check it.

good job

I think I delete some code by mistake.

could you submit a new PR (including all html files) to `docs` branch ?

**Comment by SoTosorrow** [comment]
> > Done, you can check it.
> 
> good job
> 
> I think I delete some code by mistake.
> 
> could you submit a new PR (including all html files) to `docs` branch ?

Yes, have submit on #226

**Comment by PikachuHyA** [comment]
👏👏👏👏

**Comment by SoTosorrow** [comment]
> 👏👏👏👏

you can run `gen_doc.sh` again to check if it works correctly in your environment.
I can also optimize the gen_doc.sh or supplement the documentation later if you need 

by the way, Do these changes of config need to be merged into the `main` branch?

**Comment by SoTosorrow** [comment]
@luzhixing12345 you can check the doc for current version, all these problems I think it is actually the reason of the config syntax does not match the version of vitepress.

**Comment by PikachuHyA** [comment]
> by the way, Do these changes of config need to be merged into the main branch?

Done.
