### ISSUE TITLE
[easylog]Will record_t objects take a lot of memory?

### ISSUE THREAD

**Issue by czlitony** [alibaba/yalantinglibs#222]
https://github.com/alibaba/yalantinglibs/blob/d574fa94e9b44ae270a314b495f3d487ac8a2bab/include/easylog/easylog.h#L153
If there are many log lines in a project, each line of the log will generate a record_t object, will this take a lot of memory?

**Comment by qicosmos** [comment]
no, it is a temporary string, will free after 
```
ELOG<<xx<<yy; //will call  GET_STRING to generate temp string, and the temporary will be freed after the current expression finished;

// here the temporary has been freed
```

**Comment by czlitony** [comment]
Oh, I misunderstood it, thank you for the clarification.

**Another question:**
`GET_STRING` will create a `refvalue::meta_string` variable at compile time, so there will be many `refvalue::meta_string` objects generated at compile time, right? 
```
#define GET_STRING(filename, line)                              \
  [] {                                                          \
    constexpr auto path = refvalue::meta_string{filename};      \
    constexpr size_t pos =                                      \
        path.rfind(std::filesystem::path::preferred_separator); \
    constexpr auto name = path.substr<pos + 1>();               \
    constexpr auto prefix = name + ":" + TO_STR(line);          \
    return "[" + prefix + "] ";                                 \
  }()
```

**Comment by qicosmos** [comment]
> Oh, I misunderstood it, thank you for the clarification.
> 
> **Another question:** `GET_STRING` will create a `refvalue::meta_string` variable at compile time, so there will be many `refvalue::meta_string` objects generated at compile time, right?
> 
> ```
> #define GET_STRING(filename, line)                              \
>   [] {                                                          \
>     constexpr auto path = refvalue::meta_string{filename};      \
>     constexpr size_t pos =                                      \
>         path.rfind(std::filesystem::path::preferred_separator); \
>     constexpr auto name = path.substr<pos + 1>();               \
>     constexpr auto prefix = name + ":" + TO_STR(line);          \
>     return "[" + prefix + "] ";                                 \
>   }()
> ```

Not correctly, the macro only generate a short compile-time string, such as: 
```
coro_rpc_server.hpp:235
coro_rpc_client.hpp:35
```
