### ISSUE TITLE
编译警告

### ISSUE THREAD

**Issue by lordoffox** [alibaba/yalantinglibs#233]
gcc12编译出现多条警告，看描述是检测到缓冲区溢出，不知道有没有影响

[ 59%] Building CXX object src/coro_rpc/tests/CMakeFiles/test_rpc.dir/test_coro_rpc_server.cpp.o
In file included from /home/evan/yalantinglibs/include/struct_pack/struct_pack/varint.hpp:8,
                 from /home/evan/yalantinglibs/include/struct_pack/struct_pack/struct_pack_impl.hpp:42,
                 from /home/evan/yalantinglibs/include/struct_pack/struct_pack.hpp:22,
                 from /home/evan/yalantinglibs/include/coro_rpc/coro_rpc/protocol/coro_rpc_protocol.hpp:27,
                 from /home/evan/yalantinglibs/include/coro_rpc/coro_rpc/coro_rpc_client.hpp:35,
                 from /home/evan/yalantinglibs/include/coro_rpc/coro_rpc_client.hpp:17,
                 from /home/evan/yalantinglibs/src/coro_rpc/tests/test_coro_rpc_server.cpp:19:
/home/evan/yalantinglibs/include/struct_pack/struct_pack/reflection.h: In member function ‘std::vector<std::byte> coro_rpc::coro_rpc_client::prepare_buffer(Args&& ...) [with auto func = &ns_login::LoginService::login; Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}]’:
/home/evan/yalantinglibs/include/struct_pack/struct_pack/reflection.h:85:13: warning: writing 4 bytes into a region of size 0 [-Wstringop-overflow=]
   85 |       memcpy(buffer, data, len);
      |             ^
/home/evan/yalantinglibs/include/struct_pack/struct_pack/reflection.h:85:13: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
/home/evan/yalantinglibs/include/struct_pack/struct_pack/reflection.h:85:13: warning: writing 4 bytes into a region of size 0 [-Wstringop-overflow=]
/home/evan/yalantinglibs/include/struct_pack/struct_pack/reflection.h:85:13: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
/home/evan/yalantinglibs/include/struct_pack/struct_pack/reflection.h:85:13: warning: writing 4 bytes into a region of size 0 [-Wstringop-overflow=]
/home/evan/yalantinglibs/include/struct_pack/struct_pack/reflection.h:85:13: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
/home/evan/yalantinglibs/include/struct_pack/struct_pack/reflection.h: In member function ‘std::vector<std::byte> coro_rpc::coro_rpc_client::prepare_buffer(Args&& ...) [with auto func = large_arg_fun; Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}]’:
/home/evan/yalantinglibs/include/struct_pack/struct_pack/reflection.h:85:13: warning: writing 4 bytes into a region of size 0 [-Wstringop-overflow=]

**Comment by poor-circle** [comment]
这个应该是误报。之后我会看一下怎么想办法让它不再警告。

**Comment by poor-circle** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=Wstringop-overflow
I believe this is a false warning. The warning only appears on Release mode. (no wanring on Debug mode)

**Comment by lordoffox** [comment]
原来是误报，那就没问题了
