### ISSUE TITLE
centos7.8 gcc10.2 build easylog err

### ISSUE THREAD

**Issue by gooker** [alibaba/yalantinglibs#247]
### Search before asking

- [] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen

In file included from /mnt/hgfs/vmshare/github/ylt/yalantinglibs-0.1.0/include/easylog/appender.hpp:25,
                 from /mnt/hgfs/vmshare/github/ylt/yalantinglibs-0.1.0/include/easylog/easylog.h:22,
                 from /mnt/hgfs/vmshare/github/ylt/yalantinglibs-0.1.0/include/coro_rpc/coro_rpc/async_connection.hpp:31,
                 from /mnt/hgfs/vmshare/github/ylt/yalantinglibs-0.1.0/include/coro_rpc/coro_rpc/async_rpc_server.hpp:27,
                 from /mnt/hgfs/vmshare/github/ylt/yalantinglibs-0.1.0/src/coro_rpc/tests/test_async_rpc_server.cpp:18:
/mnt/hgfs/vmshare/github/ylt/yalantinglibs-0.1.0/include/easylog/record.hpp:163:13: error: ‘string’ in namespace ‘std::pmr’ does not name a type
  163 |   std::pmr::string ss_{&resource_};
      |             ^~~~~~
/mnt/hgfs/vmshare/github/ylt/yalantinglibs-0.1.0/include/easylog/record.hpp: In member function ‘const char* easylog::record_t::get_message() const’:
/mnt/hgfs/vmshare/github/ylt/yalantinglibs-0.1.0/include/easylog/record.hpp:89:44: error: ‘ss_’ was not declared in this scope
   89 |   const char *get_message() const { return ss_.data(); }

### Reproduction way
#cmake version 3.23.3 
#gcc version 10.2.1 20210130 (Red Hat 10.2.1-11) (GCC)

mkdir build && cd build && cmake .. && make 

### Anything else
[The first version of yalantinglibs](https://github.com/alibaba/yalantinglibs/releases/tag/v0.1.0)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by qicosmos** [comment]
It has been fixed in main branch, you can use the latest code.

**Comment by gooker** [comment]
[ 99%] Built target easylog_benchmark
[ 99%] Building CXX object src/coro_http/examples/CMakeFiles/coro_http_example.dir/main.cpp.o
[100%] Linking CXX executable coro_http_example
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: CMakeFiles/coro_http_example.dir/main.cpp.o: in function `async_simple::Executor::schedule(std::function<void ()>, std::chrono::duration<long, std::ratio<1l, 1000000l> >)':
main.cpp:(.text._ZN12async_simple8Executor8scheduleESt8functionIFvvEENSt6chrono8durationIlSt5ratioILl1ELl1000000EEEE[_ZN12async_simple8Executor8scheduleESt8functionIFvvEENSt6chrono8durationIlSt5ratioILl1ELl1000000EEEE]+0xb0): undefined reference to `pthread_create'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: CMakeFiles/coro_http_example.dir/main.cpp.o: in function `asio::detail::scheduler::shutdown()':
main.cpp:(.text._ZN4asio6detail9scheduler8shutdownEv[_ZN4asio6detail9scheduler8shutdownEv]+0x147): undefined reference to `pthread_join'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail9scheduler8shutdownEv[_ZN4asio6detail9scheduler8shutdownEv]+0x16e): undefined reference to `pthread_detach'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: CMakeFiles/coro_http_example.dir/main.cpp.o: in function `asio::detail::scheduler::~scheduler()':
main.cpp:(.text._ZN4asio6detail9schedulerD2Ev[_ZN4asio6detail9schedulerD5Ev]+0x18f): undefined reference to `pthread_join'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail9schedulerD2Ev[_ZN4asio6detail9schedulerD5Ev]+0x1b6): undefined reference to `pthread_detach'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: CMakeFiles/coro_http_example.dir/main.cpp.o: in function `asio::detail::scheduler::~scheduler()':
main.cpp:(.text._ZN4asio6detail9schedulerD0Ev[_ZN4asio6detail9schedulerD5Ev]+0x19e): undefined reference to `pthread_join'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail9schedulerD0Ev[_ZN4asio6detail9schedulerD5Ev]+0x1c6): undefined reference to `pthread_detach'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: CMakeFiles/coro_http_example.dir/main.cpp.o: in function `asio::detail::resolver_service<asio::ip::tcp>::notify_fork(asio::execution_context::fork_event)':
main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEE11notify_forkENS_17execution_context10fork_eventE[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEE11notify_forkENS_17execution_context10fork_eventE]+0x107): undefined reference to `pthread_join'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEE11notify_forkENS_17execution_context10fork_eventE[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEE11notify_forkENS_17execution_context10fork_eventE]+0x12b): undefined reference to `pthread_detach'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: CMakeFiles/coro_http_example.dir/main.cpp.o: in function `asio::detail::resolver_service<asio::ip::tcp>::shutdown()':
main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEE8shutdownEv[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEE8shutdownEv]+0x2f7): undefined reference to `pthread_join'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEE8shutdownEv[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEE8shutdownEv]+0x31b): undefined reference to `pthread_detach'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEE8shutdownEv[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEE8shutdownEv]+0x33f): undefined reference to `pthread_join'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEE8shutdownEv[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEE8shutdownEv]+0x36a): undefined reference to `pthread_detach'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: CMakeFiles/coro_http_example.dir/main.cpp.o: in function `asio::detail::resolver_service<asio::ip::tcp>::~resolver_service()':
main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED2Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0x391): undefined reference to `pthread_detach'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED2Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0x517): undefined reference to `pthread_join'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED2Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0x53e): undefined reference to `pthread_detach'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED2Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0x557): undefined reference to `pthread_join'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED2Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0x57b): undefined reference to `pthread_detach'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED2Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0x5a7): undefined reference to `pthread_join'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED2Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0x5ce): undefined reference to `pthread_detach'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: CMakeFiles/coro_http_example.dir/main.cpp.o: in function `asio::detail::resolver_service<asio::ip::tcp>::~resolver_service()':
main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED0Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0x39b): undefined reference to `pthread_detach'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED0Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0x517): undefined reference to `pthread_join'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED0Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0x542): undefined reference to `pthread_detach'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED0Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0x557): undefined reference to `pthread_join'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED0Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0x57f): undefined reference to `pthread_detach'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED0Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0x5a7): undefined reference to `pthread_join'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail16resolver_serviceINS_2ip3tcpEED0Ev[_ZN4asio6detail16resolver_serviceINS_2ip3tcpEED5Ev]+0x5d2): undefined reference to `pthread_detach'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: CMakeFiles/coro_http_example.dir/main.cpp.o: in function `asio::detail::scheduler::scheduler(asio::execution_context&, int, bool, asio::detail::scheduler_task* (*)(asio::execution_context&))':
main.cpp:(.text._ZN4asio6detail9schedulerC2ERNS_17execution_contextEibPFPNS0_14scheduler_taskES3_E[_ZN4asio6detail9schedulerC5ERNS_17execution_contextEibPFPNS0_14scheduler_taskES3_E]+0x223): undefined reference to `pthread_condattr_setclock'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail9schedulerC2ERNS_17execution_contextEibPFPNS0_14scheduler_taskES3_E[_ZN4asio6detail9schedulerC5ERNS_17execution_contextEibPFPNS0_14scheduler_taskES3_E]+0x273): undefined reference to `pthread_sigmask'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail9schedulerC2ERNS_17execution_contextEibPFPNS0_14scheduler_taskES3_E[_ZN4asio6detail9schedulerC5ERNS_17execution_contextEibPFPNS0_14scheduler_taskES3_E]+0x2b8): undefined reference to `pthread_create'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail9schedulerC2ERNS_17execution_contextEibPFPNS0_14scheduler_taskES3_E[_ZN4asio6detail9schedulerC5ERNS_17execution_contextEibPFPNS0_14scheduler_taskES3_E]+0x2ec): undefined reference to `pthread_sigmask'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZN4asio6detail9schedulerC2ERNS_17execution_contextEibPFPNS0_14scheduler_taskES3_E[_ZN4asio6detail9schedulerC5ERNS_17execution_contextEibPFPNS0_14scheduler_taskES3_E]+0x3d0): undefined reference to `pthread_sigmask'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: CMakeFiles/coro_http_example.dir/main.cpp.o: in function `cinatra::coro_http_client::coro_http_client()':
main.cpp:(.text._ZN7cinatra16coro_http_clientC2Ev[_ZN7cinatra16coro_http_clientC5Ev]+0x5cf): undefined reference to `pthread_create'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: CMakeFiles/coro_http_example.dir/main.cpp.o: in function `auto asio_util::async_connect<asio::io_context::basic_executor_type<std::allocator<void>, 0ul> >(asio::io_context::basic_executor_type<std::allocator<void>, 0ul> const&, asio::basic_stream_socket<asio::ip::tcp, asio::any_io_executor>&, std::string const&, std::string const&)::{lambda(auto:1)#1}::operator()<asio_util::callback_awaitor_base<std::error_code, asio_util::callback_awaitor<std::error_code> >::awaitor_handler>(asio_util::callback_awaitor_base<std::error_code, asio_util::callback_awaitor<std::error_code> >::awaitor_handler) const':
main.cpp:(.text._ZZN9asio_util13async_connectIN4asio10io_context19basic_executor_typeISaIvELm0EEEEEN12async_simple4coro4LazyISt10error_codeEERKT_RNS1_19basic_stream_socketINS1_2ip3tcpENS1_15any_io_executorEEERKSsSL_ENKUlSB_E_clINS_21callback_awaitor_baseIS9_NS_16callback_awaitorIS9_EEE15awaitor_handlerEEEDaSB_[_ZZN9asio_util13async_connectIN4asio10io_context19basic_executor_typeISaIvELm0EEEEEN12async_simple4coro4LazyISt10error_codeEERKT_RNS1_19basic_stream_socketINS1_2ip3tcpENS1_15any_io_executorEEERKSsSL_ENKUlSB_E_clINS_21callback_awaitor_baseIS9_NS_16callback_awaitorIS9_EEE15awaitor_handlerEEEDaSB_]+0x3eb): undefined reference to `pthread_create'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: main.cpp:(.text._ZZN9asio_util13async_connectIN4asio10io_context19basic_executor_typeISaIvELm0EEEEEN12async_simple4coro4LazyISt10error_codeEERKT_RNS1_19basic_stream_socketINS1_2ip3tcpENS1_15any_io_executorEEERKSsSL_ENKUlSB_E_clINS_21callback_awaitor_baseIS9_NS_16callback_awaitorIS9_EEE15awaitor_handlerEEEDaSB_[_ZZN9asio_util13async_connectIN4asio10io_context19basic_executor_typeISaIvELm0EEEEEN12async_simple4coro4LazyISt10error_codeEERKT_RNS1_19basic_stream_socketINS1_2ip3tcpENS1_15any_io_executorEEERKSsSL_ENKUlSB_E_clINS_21callback_awaitor_baseIS9_NS_16callback_awaitorIS9_EEE15awaitor_handlerEEEDaSB_]+0x4b4): undefined reference to `pthread_detach'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: /opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/libstdc++_nonshared.a(thread48.o): in function `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())':
(.text._ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteIS1_EEPFvvE+0x11): undefined reference to `pthread_create'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: /opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/libstdc++_nonshared.a(thread48.o): in function `std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)())':
(.text._ZNSt6thread15_M_start_threadESt10shared_ptrINS_10_Impl_baseEEPFvvE+0x5e): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make[2]: *** [src/coro_http/examples/CMakeFiles/coro_http_example.dir/build.make:97：src/coro_http/examples/coro_http_example] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1502：src/coro_http/examples/CMakeFiles/coro_http_example.dir/all] 错误 2
make: *** [Makefile:146：all] 错误 2

**Comment by PikachuHyA** [comment]
it caused by typo, I will fix it

**Comment by PikachuHyA** [comment]
https://github.com/alibaba/yalantinglibs/pull/248/files

please apply this patch, and try again.

**Comment by gooker** [comment]
ok
