### ISSUE TITLE
typo in project's about

### ISSUE THREAD

**Issue by tchaikov** [alibaba/yalantinglibs#251]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen

the about section in the project's homepage on github reads:

> A collection of C++20 libraries, include coro_rpc, struct_pack, struct_json, struct_pb, easylog, asnyc_simple 

presumably, "asnyc_simple" should have been "async_simple".

### Reproduction way

fire up a web browser and point it to https://github.com/alibaba/yalantinglibs, then stare at the top-right corner for a while.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by qicosmos** [comment]
fixed.
