### ISSUE TITLE
Windows上如何生成protoc-gen-struct_pb，可以用吗

### ISSUE THREAD

**Issue by PLVQ** [alibaba/yalantinglibs#255]
### Search before asking

- [ ] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by PikachuHyA** [comment]
需要先安装protobuf，cmake检测到protobuf就会自动构建protoc-gen-struct_pb

**Comment by PikachuHyA** [comment]
稍微新一点就好了。
我自己测试的时候，protobuf 3.7不行，新版本有的API这个版本没有。
如果有遇到什么问题，可以及时反馈。

**Comment by PLVQ** [comment]
好的，谢谢哈

**Comment by PLVQ** [comment]
你好，这个是只能用protobuf的动态库方式安装后才能编译生存吗
