### ISSUE TITLE
能去掉这些编译警告吗

### ISSUE THREAD

**Issue by cpkt9762** [alibaba/yalantinglibs#257]
编译工具 Visual Studio 2022 17.5.0
 警告等级 /W4

yalantinglibs\include\easylog\record.hpp(177): warning C4267: “return”: 从“size_t”转换到“unsigned int”，可能丢失数据
yalantinglibs\include\easylog\appender.hpp(110): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
yalantinglibs\include\easylog\appender.hpp(115): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
yalantinglibs\include\coro_rpc\coro_rpc\coro_connection.hpp(308): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc\coro_rpc\coro_connection.hpp(308): note: 考虑改用 "if constexpr" 语句
yalantinglibs\include\coro_rpc\coro_rpc\coro_connection.hpp(354): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc\coro_rpc\coro_connection.hpp(354): note: 考虑改用 "if constexpr" 语句
yalantinglibs\include\coro_rpc\coro_rpc\coro_connection.hpp(363): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc\coro_rpc\coro_connection.hpp(363): note: 考虑改用 "if constexpr" 语句
yalantinglibs\include\coro_rpc\coro_rpc\coro_connection.hpp(406): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc\coro_rpc\coro_connection.hpp(411): note: 考虑改用 "if constexpr" 语句
yalantinglibs\include\util\string_finder.hpp(49): warning C4100: “keyword”: 未引用的形参
yalantinglibs\include\util\string_finder.hpp(80): warning C4100: “keyword”: 未引用的形参
yalantinglibs\include\coro_rpc\coro_rpc\protocol\coro_rpc_protocol.hpp(125): warning C4267: “=”: 从“size_t”转换到“uint32_t”，可能丢失数据
yalantinglibs\include\coro_rpc\coro_rpc\protocol\coro_rpc_protocol.hpp(112): warning C4100: “req_header”: 未引用的形参

yalantinglibs\include\coro_rpc\coro_rpc\coro_rpc_server.hpp(110): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(110): note: 考虑改用 "if constexpr" 语句
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(104): note: 在编译 类 模板 成员函数“std::errc coro_rpc::coro_rpc_server_base<coro_rpc::config::coro_rpc_default_config>::start(void) noexcept”时
 
yalantinglibs\include\coro_rpc\coro_rpc\coro_rpc_server.hpp(113): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(113): note: 考虑改用 "if constexpr" 语句
yalantinglibs\include\coro_rpc\coro_rpc\coro_rpc_server.hpp(87): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(87): note: 考虑改用 "if constexpr" 语句
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(86): note: 在编译 类 模板  
  
yalantinglibs\include\coro_rpc\coro_rpc\coro_rpc_server.hpp(358): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(358): note: 考虑改用 "if constexpr" 语句
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(342): note: 在编译 类 模板 成员函数“async_simple::coro::Lazy<std::errc> coro_rpc::coro_rpc_server_base<coro_rpc::config::coro_rpc_default_config>::accept(void)”时
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(134): note: 查看对正在编译的函数 模板 实例化“async_simple::coro::Lazy<std::errc> coro_rpc::coro_rpc_server_base<coro_rpc::config::coro_rpc_default_config>::accept(void)”的引用
yalantinglibs\include\coro_rpc\coro_rpc\coro_rpc_server.hpp(366): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(366): note: 考虑改用 "if constexpr" 语句
yalantinglibs\include\coro_rpc\coro_rpc\coro_rpc_server.hpp(309): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(309): note: 考虑改用 "if constexpr" 语句
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(308): note: 在编译 类 模板 成员函数“std::errc coro_rpc::coro_rpc_server_base<coro_rpc::config::coro_rpc_default_config>::listen(void)”时
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(118): note: 查看对正在编译的函数 模板 实例化“std::errc coro_rpc::coro_rpc_server_base<coro_rpc::config::coro_rpc_default_config>::listen(void)”的引用
yalantinglibs\include\coro_rpc\coro_rpc\coro_rpc_server.hpp(319): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(320): note: 考虑改用 "if constexpr" 语句
yalantinglibs\include\coro_rpc\coro_rpc\coro_rpc_server.hpp(332): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(333): note: 考虑改用 "if constexpr" 语句
yalantinglibs\include\coro_rpc\coro_rpc\coro_rpc_server.hpp(338): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(338): note: 考虑改用 "if constexpr" 语句
yalantinglibs\include\coro_rpc\coro_rpc\coro_rpc_server.hpp(194): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(194): note: 考虑改用 "if constexpr" 语句
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(188): note: 在编译 类 模板 成员函数“void coro_rpc::coro_rpc_server_base<coro_rpc::config::coro_rpc_default_config>::stop(void)”时
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(88): note: 查看对正在编译的函数 模板 实例化“void coro_rpc::coro_rpc_server_base<coro_rpc::config::coro_rpc_default_config>::stop(void)”的引用
yalantinglibs\include\coro_rpc\coro_rpc\coro_rpc_server.hpp(199): warning C4456: “lock”的声明隐藏了上一个本地声明
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(189): note: 参见“lock”的声明
yalantinglibs\include\coro_rpc\coro_rpc\coro_rpc_server.hpp(209): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(209): note: 考虑改用 "if constexpr" 语句
yalantinglibs\include\coro_rpc\coro_rpc\coro_rpc_server.hpp(211): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(211): note: 考虑改用 "if constexpr" 语句
yalantinglibs\include\coro_rpc\coro_rpc\coro_rpc_server.hpp(217): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(217): note: 考虑改用 "if constexpr" 语句
yalantinglibs\include\easylog\easylog.h(80): warning C4996: 'localtime': This function or variable may be unsafe. Consider using localtime_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  yalantinglibs\include\easylog/easylog.h(87): note: 查看对正在编译的函数 模板 实例化“size_t easylog::logger<0>::get_time_str<32,std::chrono::system_clock::time_point>(char (&)[32],const _T0 &)”的引用
          with
          [
              _T0=std::chrono::system_clock::time_point
          ]
  yalantinglibs\include\easylog/easylog.h(87): note: 查看对正在编译的函数 模板 实例化“size_t easylog::logger<0>::get_time_str<32,std::chrono::system_clock::time_point>(char (&)[32],const _T0 &)”的引用
          with
          [
              _T0=std::chrono::system_clock::time_point
          ]
  yalantinglibs\include\easylog/easylog.h(85): note: 在编译 类 模板 成员函数“void easylog::logger<0>::append_format(const easylog::record_t &)”时
  yalantinglibs\include\easylog/easylog.h(37): note: 查看对正在编译的函数 模板 实例化“void easylog::logger<0>::append_format(const easylog::record_t &)”的引用
  yalantinglibs\include\coro_rpc\coro_rpc\coro_connection.hpp(137): note: 查看对正在编译的 类 模板 实例化“easylog::logger<0>”的引用
yalantinglibs\include\coro_rpc\coro_rpc\coro_connection.hpp(137): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc\coro_rpc\coro_connection.hpp(125): note: 考虑改用 "if constexpr" 语句
  yalantinglibs\include\coro_rpc\coro_rpc\coro_connection.hpp(97): note: 查看对正在编译的函数 模板 实例化“async_simple::coro::Lazy<void> coro_rpc::coro_connection::start_impl<coro_rpc::config::coro_rpc_default_config::rpc_protocol,asio::ip::tcp::socket>(coro_rpc::protocol::coro_rpc_protocol::router &,Socket &) noexcept”的引用
          with
          [
              Socket=asio::ip::tcp::socket
          ]
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(391): note: 查看对正在编译的函数 模板 实例化“async_simple::coro::Lazy<void> coro_rpc::coro_connection::start<coro_rpc::config::coro_rpc_default_config::rpc_protocol>(coro_rpc::protocol::coro_rpc_protocol::router &) noexcept”的引用
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(380): note: 查看对正在编译的函数 模板 实例化“async_simple::coro::Lazy<void> coro_rpc::coro_rpc_server_base<coro_rpc::config::coro_rpc_default_config>::start_one<std::shared_ptr<coro_rpc::coro_connection>>(_T0) noexcept”的引用
          with
          [
              _T0=std::shared_ptr<coro_rpc::coro_connection>
          ]
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(380): note: 查看对正在编译的函数 模板 实例化“async_simple::coro::Lazy<void> coro_rpc::coro_rpc_server_base<coro_rpc::config::coro_rpc_default_config>::start_one<std::shared_ptr<coro_rpc::coro_connection>>(_T0) noexcept”的引用
          with
          [
              _T0=std::shared_ptr<coro_rpc::coro_connection>
          ]
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(342): note: 在编译 类 模板 成员函数“async_simple::coro::Lazy<std::errc> coro_rpc::coro_rpc_server_base<coro_rpc::config::coro_rpc_default_config>::accept(void)”时
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(134): note: 查看对正在编译的函数 模板 实例化“async_simple::coro::Lazy<std::errc> coro_rpc::coro_rpc_server_base<coro_rpc::config::coro_rpc_default_config>::accept(void)”的引用
yalantinglibs\include\coro_rpc\coro_rpc\coro_connection.hpp(161): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc\coro_rpc\coro_connection.hpp(125): note: 考虑改用 "if constexpr" 语句
yalantinglibs\include\coro_rpc\coro_rpc\coro_connection.hpp(179): warning C4127: 条件表达式是常量
  yalantinglibs\include\coro_rpc\coro_rpc\coro_connection.hpp(125): note: 考虑改用 "if constexpr" 语句
yalantinglibs\include\coro_rpc\coro_rpc\router.hpp(119): warning C4267: “参数”: 从“size_t”转换到“uint32_t”，可能丢失数据
  yalantinglibs\include\coro_rpc/coro_rpc/router.hpp(174): note: 查看对正在编译的函数 模板 实例化“unsigned int coro_rpc::protocol::router<coro_rpc::protocol::coro_rpc_protocol,std::unordered_map>::auto_gen_register_key<std::string_view echo(std::string_view)>(void)”的引用
  yalantinglibs\include\coro_rpc/coro_rpc/router.hpp(180): note: 查看对正在编译的函数 模板 实例化“unsigned int coro_rpc::protocol::router<coro_rpc::protocol::coro_rpc_protocol,std::unordered_map>::auto_gen_register_key<std::string_view echo(std::string_view)>(void)”的引用
  yalantinglibs\include\coro_rpc/coro_rpc/router.hpp(402): note: 查看对正在编译的函数 模板 实例化“void coro_rpc::protocol::router<coro_rpc::protocol::coro_rpc_protocol,std::unordered_map>::regist_one_handler<std::string_view echo(std::string_view)>(void)”的引用
  yalantinglibs\include\coro_rpc/coro_rpc/router.hpp(403): note: 查看对正在编译的函数 模板 实例化“void coro_rpc::protocol::router<coro_rpc::protocol::coro_rpc_protocol,std::unordered_map>::regist_one_handler<std::string_view echo(std::string_view)>(void)”的引用
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(291): note: 查看对正在编译的函数 模板 实例化“void coro_rpc::protocol::router<coro_rpc::protocol::coro_rpc_protocol,std::unordered_map>::register_handler<std::string_view echo(std::string_view),>(void)”的引用
  yalantinglibs\include\coro_rpc/coro_rpc/coro_rpc_server.hpp(292): note: 查看对正在编译的函数 模板 实例化“void coro_rpc::protocol::router<coro_rpc::protocol::coro_rpc_protocol,std::unordered_map>::register_handler<std::string_view echo(std::string_view),>(void)”的引用

yalantinglibs\include\coro_rpc\coro_rpc\router.hpp(216): warning C4100: “obj”: 未引用的形参

**Comment by poor-circle** [comment]
OK, I will fix it later.

**Comment by sunflower-knight** [comment]
It is time to close this issuse for we have change the cmake warning config.
