### ISSUE TITLE
develop in branch website ? 

### ISSUE THREAD

**Issue by sunflower-knight** [alibaba/yalantinglibs#270]
### What happened + What you expected to happen
Now the CI for website work on branch main . It is unconvenient.
And develop will commit many time for website develop.
### Reproduction way
Create a new branch named website  will be better ?  Maybe use branch doc is also good if we can make it sync to branch main 
I will change the website building CI workflow.

And make it easy to use.
### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by PikachuHyA** [comment]
LGTM
