### ISSUE TITLE
Error C2825 using win10 VS2022

### ISSUE THREAD

**Issue by ruiyuanlu** [alibaba/yalantinglibs#292]
### Search before asking

- [ √ ] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen

Does not work for lambda expression.
On Visual Studio 2022:
Error	C2825	'Function': 当后面跟“::”时必须为类或命名空间

This should work, but not.

### Reproduction way
It is the code in `type_traits.h`:

```c++
template <typename Function>
struct function_traits;

// Support function object and lambda expression
template <class Function>
struct function_traits : function_traits<decltype(&Function::operator())> {
  constexpr int ok = 1;  // just for debugging
};

// test for lambda
auto lambdafunc = [](int a, int b) {return a + b; };
std::cout << function_traits<decltype(lambdafunc)>::ok << std::endl;
```

### Anything else
NO

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by qicosmos** [comment]
@4kangjc 看一下这个问题哈

**Comment by 4kangjc** [comment]
> ### Search before asking
> * [ √ ] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.
> 
> ### What happened + What you expected to happen
> Does not work for lambda expression. On Visual Studio 2022: Error C2825 'Function': 当后面跟“::”时必须为类或命名空间
> 
> This should work, but not.
> 
> ### Reproduction way
> It is the code in `type_traits.h`:
> 
> ```c++
> template <typename Function>
> struct function_traits;
> 
> // Support function object and lambda expression
> template <class Function>
> struct function_traits : function_traits<decltype(&Function::operator())> {
>   constexpr int ok = 1;  // just for debugging
> };
> 
> // test for lambda
> auto lambdafunc = [](int a, int b) {return a + b; };
> std::cout << function_traits<decltype(lambdafunc)>::ok << std::endl;
> ```
> 
> ### Anything else
> NO
> 
> ### Are you willing to submit a PR?
> * [ ]  Yes I am willing to submit a PR!

Can this work?
```cpp
#include <iostream>

template <typename Function>
struct function_traits;

template <typename This, typename Return, typename... Arguments>
struct function_traits<Return (This::*)(Arguments...) const> {
  static constexpr int ok = 1;
};

// Support function object and lambda expression
template <class Function>
struct function_traits : function_traits<decltype(&Function::operator())> {};

int main() {
// test for lambda
  auto lambdafunc = [](int a, int b) {return a + b; };
  std::cout << function_traits<decltype(lambdafunc)>::ok << std::endl;
}
```

**Comment by ruiyuanlu** [comment]
This works fine. Thank you.

**Comment by qicosmos** [comment]
提个pr fix 一下吧 @4kangjc

**Comment by 4kangjc** [comment]
> 提个pr fix 一下吧 @4kangjc

没问题，他给的事例有点小问题。
