### ISSUE TITLE
use std::forward in get_needed_size() will cause  wrong deserialized result 

### ISSUE THREAD

**Issue by cageq** [alibaba/yalantinglibs#299]
sample code : 

https://github.com/cageq/yalantinglibs/blob/main/examples/packdemo.cpp

if I use std::forward in get_needed_size,  I can't get correctly deserialized result  

use forward output : ( "hello" is misssing )

auto bodySize = struct_pack::get_needed_size(std::tuple<Args...>(std::forward<Args>(args)...));//buggy can't use forward 

result :
result :3333

don't use std::forward output : 
auto bodySize = struct_pack::get_needed_size(std::tuple<Args...>(args...)); 

result :hello
result :3333

I thinks get_needed_size should be readonly, shouldn't affect deserialize_to 

compiler : 
gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0

linux : 
wsl ubuntu 22.04

**Comment by poor-circle** [comment]
The serialize code can also simply as
```cpp
  return struct_pack::serialize<std::string>(args...);
}
```

**Comment by poor-circle** [comment]
the string has been moved by this construction. so it is empty when serialization.
```cpp
std::tuple<Args...>(std::forward(args)...)
```
get_needed_size() is readonly. the problem is the moving construction.

**Comment by cageq** [comment]
thanks a lot.
