### ISSUE TITLE
Members count error if existing inheritance

### ISSUE THREAD

**Issue by yanminhui** [alibaba/yalantinglibs#304]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen

```.cpp
#include <array>
#include <struct_pack/struct_pack.hpp>

struct bar1
{
};

struct bar2 
{
};

struct foo3 : bar1, bar2
{
    int a;
    double b;
    char c;
};

struct foo5 {
    int a;
    double b;
    foo3 c;
    char* d;
    std::array<int, 10> e;
};

int main() 
{
    static_assert(struct_pack::members_count<foo3> == 3); // ERROR!!!
    static_assert(struct_pack::members_count<foo5> == 5);
}
```

```.shell
admin@bryan-mbam2 ~ % clang++ -std=c++20 ylt.cpp -I ~/repos/yalantinglibs/include
ylt.cpp:29:5: error: static_assert failed due to requirement 'struct_pack::members_count<foo3> == 3'
    static_assert(struct_pack::members_count<foo3> == 3); // ERROR!!!
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Related issues:** #17 

### Anything else

**Possible solution:**

[Run this code](https://godbolt.org/z/rz8ejsfaP)
```.cpp
#include <array>
#include <type_traits>

template<class T, std::size_t N>
struct anything 
{
    template<class U>
    operator U() const;
};

template <class T, std::size_t N>
struct base 
{
    template<class U>
    requires std::derived_from<T, U>
    operator U() const;
};

template <class T, template <typename, std::size_t> class U, std::size_t... Ints>
concept constructible_with = requires 
{
    T{ U<T, Ints>{}... };
};

template <class T, template <typename, std::size_t> class Arg>
requires std::is_aggregate_v<T>
class constructor_parameter_size
{
    template <std::size_t... Ints>
    static consteval bool is_constructible(std::index_sequence<Ints...>) 
    {
        return constructible_with<T, Arg, Ints...>;
    }

    template <std::size_t N = 0u, bool found = false>
    static consteval std::size_t count() 
    {
        if constexpr (is_constructible(std::make_index_sequence<N>{})) {
            return count<N + 1, true>();
        } else if constexpr (found) {
            return N - 1;
        } else if constexpr (N == 0 && std::is_same_v<Arg<T, 0>, anything<T, 0>>) {
            return count<N + 1, found>(); // fix #84
        } else {
            return N; // TODO: go further if N == 0 ?
        }
    }

public:
    static constexpr std::size_t value = count();
};

template <class T>
requires std::is_aggregate_v<T>
inline constexpr std::size_t bases_count = constructor_parameter_size<T, base>::value;

template <class T>
requires std::is_aggregate_v<T>
inline constexpr std::size_t aggregate_size = constructor_parameter_size<T, anything>::value - bases_count<T>;

struct bar1
{
};

struct bar2 
{
};

struct foo3 : bar1, bar2
{
    int a;
    double b;
    char c;
};

struct foo5 {
    int a;
    double b;
    foo3 c;
    char* d;
    std::array<int, 10> e;
};

class Foo 
{
public:
  Foo(int foo, int bar)
  : foo_(foo), bar_(bar)
  {}

private:
    int foo_;
    int bar_;
};

struct Bar 
{
    Foo foo;
};

int main() {
    static_assert(bases_count<foo3> == 2);
    static_assert(aggregate_size<foo3> == 3);
    static_assert(bases_count<foo5> == 0);
    static_assert(aggregate_size<foo5> == 5);
    static_assert(aggregate_size<Bar> == 1);  // see #84 
}
```

**Related issues fixed:** #84 

**NOTE**: check if aggregate structure decomposable ?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by poor-circle** [comment]
You can add this to workaround it.
```cpp
template<>
constexpr std::size_t struct_pack::members_count<foo3> = 3;
```

**Comment by yanminhui** [comment]
> You can add this to workaround it.
> 
> ```c++
> template<>
> constexpr std::size_t struct_pack::members_count<foo3> = 3;
> ```

Yes, but I think it is not a good way to workaround. I have commented it in #278.

**Comment by poor-circle** [comment]
> > You can add this to workaround it.
> > ```c++
> > template<>
> > constexpr std::size_t struct_pack::members_count<foo3> = 3;
> > ```
> 
> Yes, but I think it is not a good way to workaround. I have commented it in #278.

Just Like std::hash, the specialization code shouldn't put in user namespace.

**Comment by yanminhui** [comment]
> Just Like std::hash, the specialization code shouldn't put in user namespace.

A program may add a template specialization for any standard library template to namespace `std`.

In my opinions,  don't inject your hash function into the namespace `std`, use the hash template argument of the corresponding containers (e.g. `unordered_map`).

**Comment by poor-circle** [comment]
> > Just Like std::hash, the specialization code shouldn't put in user namespace.
> 
> A program may add a template specialization for any standard library template to namespace `std`.
> 
> In my opinions, don't inject your hash function into the namespace `std`, use the template argument `Hash` of the corresponding containers (e.g. `unordered_map`).

Now struct_pack has a macro STRUCT_PACK_REFL to support non-aggregated type.
It works on ADL, so user can use the macro in the same namespace of type.

**Comment by poor-circle** [comment]
#382
