### ISSUE TITLE
Compilation error occurred during compilation using gcc-11

### ISSUE THREAD

**Issue by ttbachyinsda** [alibaba/yalantinglibs#313]
### Search before asking

- [ ] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen

[ 91%] Building CXX object src/coro_rpc/examples/channel/CMakeFiles/rpc_channel_example.dir/main.cpp.o
In file included from /opt/rh/devtoolset-11/root/usr/include/c++/11/string:55,
                 from /opt/rh/devtoolset-11/root/usr/include/c++/11/stdexcept:39,
                 from /opt/rh/devtoolset-11/root/usr/include/c++/11/system_error:41,
                 from /opt/rh/devtoolset-11/root/usr/include/c++/11/bits/std_mutex.h:39,
                 from /opt/rh/devtoolset-11/root/usr/include/c++/11/bits/atomic_wait.h:49,
                 from /opt/rh/devtoolset-11/root/usr/include/c++/11/bits/atomic_base.h:41,
                 from /opt/rh/devtoolset-11/root/usr/include/c++/11/atomic:41,
                 from /disk1/yalantinglibs/src/coro_rpc/examples/channel/main.cpp:16:
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/basic_string.h: In instantiation of ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = std::basic_string<char>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’:
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/basic_string.h:5201:27:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = std::basic_string<char>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/basic_string.h:3736:28:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(_InputIterator, _InputIterator, const _Alloc&) [with _InputIterator = std::basic_string<char>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
/disk1/yalantinglibs/src/coro_rpc/examples/channel/main.cpp:92:69:   required from here
/opt/rh/devtoolset-11/root/usr/include/c++/11/bits/basic_string.h:5179:76: error: no type named ‘iterator_category’ in ‘struct std::iterator_traits<std::basic_string<char> >’
 5179 |           typedef typename iterator_traits<_InIterator>::iterator_category _Tag;
      |                                                                            ^~~~

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by poor-circle** [comment]
I will fix it later.

**Comment by poor-circle** [comment]
I can't reproduce it with gcc 11.4.0.
Could you give me more info about your environment?

**Comment by ttbachyinsda** [comment]
$gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-11/root/usr --mandir=/opt/rh/devtoolset-11/root/usr/share/man --infodir=/opt/rh/devtoolset-11/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-11.2.1-20220127/obj-x86_64-redhat-linux/isl-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.1 20220127 (Red Hat 11.2.1-9) (GCC)
