### ISSUE TITLE
struct_pack::serialize error

### ISSUE THREAD

**Issue by 982945902** [alibaba/yalantinglibs#314]
this is my struct :
`  struct deserU {
    std::string type_;
    ssize_t numel_ = 0;
    ssize_t stride_ = 0;
    ssize_t offset_ = 0;
  };`

this is my encode example:
`
makeBuffer(struct_pack::serialize<std::string>(
              deserU{eltype_.toString(), numel_, stride_, offset_})
`
```
inline Buffer makeBuffer(std::string&& buf) { return Buffer(buf); }

class Buffer final {
  // friend inline std::ostream& operator<<(std::ostream& out, const Buffer& v);
  std::shared_ptr<std::string> buf_ = std::make_shared<std::string>();

 public:
  void resize(size_t size) { buf_->resize(size); }
  size_t size() const { return buf_->size(); }

  Buffer() = default;
  ~Buffer() = default;

  Buffer(const Buffer& other) { buf_ = other.buf_; }
  Buffer(Buffer&& other) { buf_ = other.buf_; }

  Buffer(std::string&& str) : buf_(std::make_shared<std::string>(str)) {}

  Buffer& operator=(const Buffer& other) {
    buf_ = other.buf_;
    return *this;
  }
  Buffer& operator=(Buffer&& other) {
    buf_ = other.buf_;
    return *this;
  }

  Buffer(const std::string& str) : buf_(std::make_shared<std::string>(str)) {}

  Buffer(const void* data, size_t size)
      : buf_(std::make_shared<std::string>(static_cast<const char*>(data),
                                           size)) {}

  template <typename T = void>
  auto data() {
    return (T*)(buf_->data());
  }

  template <typename T = void>
  auto data() const {
    return (const T*)(buf_->data());
  }

  Buffer clone() const {
    Buffer buff;
    buff.resize(buf_->size());
    std::memcpy(buff.data<std::byte>(), data<std::byte>(), buf_->size());

    return buff;
  }

  std::string& to_string() { return *buf_; }

  const std::string& string() const { return *buf_; }

  template <typename T>
  std::span<T> to_span() const {
    return {buf_->data(), buf_->size() / sizeof(T)};
  }

  std::string_view to_string_view() const {
    return {buf_->data(), buf_->size()};
  }
};
```

after serialize, normal case, return  string size is 55, but somtimes is will be 274941616272 or 274941615664 ..etc

**Comment by 982945902** [comment]
i use brpc multi thread to call struct_pack::serialize

**Comment by poor-circle** [comment]
struct_pack::serialize is readonly & thread-safe.

**Comment by poor-circle** [comment]
I afraid the bug is in some thread unsafe operation to Buffer. 
Could you try to add a assert like:
```
assert(eltype_.size()<100000)
auto ret=serialize(……);
assert(ret.size()<1000000);
```
to confirm if the problem is in struct_pack?

**Comment by 982945902** [comment]
> I afraid the bug is in some thread unsafe operation to Buffer. Could you try to add a assert like:
> 
> ```
> assert(eltype_.size()<100000)
> auto ret=serialize(……);
> assert(ret.size()<1000000);
> ```
> 
> to confirm if the problem is in struct_pack?

sorry, my code have some multi thread bug cause.    

if you have any plan to support class private variables?

**Comment by poor-circle** [comment]
I will support it later. Then we can write some code to support non-aggregate type and private member like
```cpp
class foo 
{
  std::string a;
  std::string b;
  STRUCT_PACK_DEFINE(a,b);
}
```

**Comment by poor-circle** [comment]
> I will support it later. Then we can write some code to serialize non-aggregate type and private member like
> 
> ```c++
> class foo 
> {
>   std::string a;
>   std::string b;
>   STRUCT_PACK_DEFINE(a,b);
> }
> ```

It's impossible to serialize private member without some intrusive code.

**Comment by poor-circle** [comment]
> > I afraid the bug is in some thread unsafe operation to Buffer. Could you try to add a assert like:
> > ```
> > assert(eltype_.size()<100000)
> > auto ret=serialize(……);
> > assert(ret.size()<1000000);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to confirm if the problem is in struct_pack?
> 
> sorry, my code have some multi thread bug cause.
> 
> if you have any plan to support class private variables?

supported by #384
