### ISSUE TITLE
struct_json定义的结构体是复杂数据类型时的问题

### ISSUE THREAD

**Issue by tornado96** [alibaba/yalantinglibs#332]
当使用struct_json::from_json进行反序列化时，若对应的结构体包含了vector，map数据类型时，会报错。例如，定义的struct为：
struct{
  std::vector<std::string> A;
  std::map<std::string, int> B;
}
报错：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2672	“parse_item”: 未找到匹配的重载函数yalantinglibs-0.1.1\thirdparty\iguana\iguana\json_reader.hpp	576	

请问，复杂结构体，如何实现序列化和反序列化？

**Comment by qicosmos** [comment]
你少定义了一个REFELCTION宏，没有任何问题哈。
```c++
struct Some{
    std::vector<std::string> A;
    std::map<std::string, int> B;
};
REFLECTION(Some, A, B);

// example
Some some{};// init it.
std::string str;
iguana::to_json(some, str);
Some some1{};
iguana::from_json(some1, str);
```
