### ISSUE TITLE
CMake fails to compile project

### ISSUE THREAD

**Issue by SPECIALTIGER-007** [alibaba/yalantinglibs#369]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen
When I try to compile using CMake following the tutorial, I get compilation errors.
My command is as follows:
```
mkdir build && cd build
cmake ..
```
everything is correct.
The prompt returned by command:
`` The CXX compiler identification is GNU 11.3.0``
comply with the specified compiler version requirements.

Then when I try to run the command
``cmake --build . --config debug``, an error occurred.

When ``Built target coro_rpc_benchmark_client``,
it generate benchmark data, and something wrong happened.
```
Built target coro_rpc_benchmark_client
Building CXX object src/coro_rpc/benchmark/CMakeFiles/coro_rpc_benchmark_data_gen.dir/data_gen.cpp.o
Linking CXX executable ../../../output/benchmark/coro_rpc_benchmark_data_gen
generate benchmark data
2023-07-16 13:54:30.157 INFO     [22699] [coro_rpc_server.hpp:286] begin to listen
2023-07-16 13:54:30.157 INFO     [22699] [coro_rpc_server.hpp:315] listen port 42839 successfully
2023-07-16 13:54:30.157 INFO     [22699] [coro_rpc_client.hpp:391] client_id 0 begin to connect 42839
2023-07-16 13:54:30.158 INFO     [22703] [coro_rpc_server.hpp:345] new client conn_id 1 coming
2023-07-16 13:54:30.158 ERROR    [22704] [router.hpp:272] the rpc function not registered, function ID: 1103691076
2023-07-16 13:54:30.158 ERROR    [22704] [coro_connection.hpp:420] Function not implemented, resp_err_
2023-07-16 13:54:30.159 INFO     [22707] [coro_rpc_client.hpp:347] client_id 0 close
2023-07-16 13:54:30.159 ERROR    [22699] [coro_rpc_client.hpp:280] client has been closed, please re-connect
2023-07-16 13:54:30.159 ERROR    [22699] [coro_rpc_client.hpp:280] client has been closed, please re-connect
2023-07-16 13:54:30.159 ERROR    [22699] [coro_rpc_client.hpp:280] client has been closed, please re-connect
2023-07-16 13:54:30.159 ERROR    [22699] [coro_rpc_client.hpp:280] client has been closed, please re-connect
2023-07-16 13:54:30.159 ERROR    [22699] [coro_rpc_client.hpp:280] client has been closed, please re-connect
2023-07-16 13:54:30.159 ERROR    [22699] [coro_rpc_client.hpp:280] client has been closed, please re-connect
2023-07-16 13:54:30.159 ERROR    [22699] [coro_rpc_client.hpp:280] client has been closed, please re-connect
2023-07-16 13:54:30.159 ERROR    [22699] [coro_rpc_client.hpp:280] client has been closed, please re-connect
2023-07-16 13:54:30.159 ERROR    [22699] [coro_rpc_client.hpp:280] client has been closed, please re-connect
2023-07-16 13:54:30.159 ERROR    [22699] [coro_rpc_client.hpp:280] client has been closed, please re-connect
2023-07-16 13:54:30.159 ERROR    [22699] [coro_rpc_client.hpp:280] client has been closed, please re-connect
2023-07-16 13:54:30.159 ERROR    [22699] [coro_rpc_client.hpp:280] client has been closed, please re-connect
2023-07-16 13:54:30.159 ERROR    [22699] [coro_rpc_client.hpp:280] client has been closed, please re-connect
2023-07-16 13:54:30.159 ERROR    [22699] [coro_rpc_client.hpp:280] client has been closed, please re-connect
2023-07-16 13:54:30.159 ERROR    [22699] [coro_rpc_client.hpp:280] client has been closed, please re-connect
2023-07-16 13:54:30.159 ERROR    [22699] [coro_rpc_client.hpp:280] client has been closed, please re-connect
2023-07-16 13:54:30.159 ERROR    [22699] [coro_rpc_client.hpp:280] client has been closed, please re-connect
2023-07-16 13:54:30.159 ERROR    [22699] [coro_rpc_client.hpp:280] client has been closed, please re-connect
2023-07-16 13:54:30.159 INFO     [22703] [coro_rpc_server.hpp:335] accept failed, error: Operation aborted.
2023-07-16 13:54:30.159 INFO     [22699] [coro_rpc_server.hpp:176] begin to stop coro_rpc_server, conn size 0
2023-07-16 13:54:30.159 INFO     [22699] [coro_rpc_server.hpp:191] wait for server's thread-pool finish all work.
2023-07-16 13:54:30.159 INFO     [22699] [coro_rpc_server.hpp:193] server's thread-pool finished.
```

Importantly, When compilation proceeds to ``Built target protoc-gen-struct_pb``, the compilation exited abnormally.
```
Building CXX object src/struct_pb/protoc-plugin/CMakeFiles/protoc-gen-struct_pb.dir/main.cpp.o
Linking CXX executable ../../../output/bin/protoc-gen-struct_pb
Built target protoc-gen-struct_pb
src/struct_pack/benchmark/CMakeFiles/struct_pack_benchmark.dir/build.make:73: *** target pattern contains no '%'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:1123: src/struct_pack/benchmark/CMakeFiles/struct_pack_benchmark.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```
I don't konw what happened.

### Are you willing to submit a PR?
- [x] Yes I am willing to submit a PR!

**Comment by poor-circle** [comment]
Could you try to add cmake option `-DGENERATE_BENCHMARK_DATA` & `-DBUILD_STRUCT_PB` ?

**Comment by SPECIALTIGER-007** [comment]
@poor-circle 
You mean  `cmake ..  -DGENERATE_BENCHMARK_DATA -DBUILD_STRUCT_PB` ?
I tried and it runned error.
```
CMake Error: Parse error in command line argument: GENERATE_BENCHMARK_DATA
 Should be: VAR:type=value

CMake Error: Run 'cmake --help' for all supported options.
```
I also tried `cmake ..` and `cmake --build . -DGENERATE_BENCHMARK_DATA -DBUILD_STRUCT_PB`，it also runned error.
```
Unknown argument -DGENERATE_BENCHMARK_DATA
```

**Comment by poor-circle** [comment]
> 

sorry, I mean 'cmake ..  -DGENERATE_BENCHMARK_DATA=OFF -DBUILD_STRUCT_PB=OFF'

**Comment by SPECIALTIGER-007** [comment]
I try to run there commands.
```
cmake ..  -DGENERATE_BENCHMARK_DATA=OFF -DBUILD_STRUCT_PB=OFF
cmake --build . --config debug -j
```
It exits.
```
...
[ 33%] Building CXX object src/coro_rpc/tests/CMakeFiles/coro_rpc_regist_test_3.dir/test_register_duplication_3.cpp.o
src/struct_pack/benchmark/CMakeFiles/struct_pack_benchmark.dir/build.make:73: *** target pattern contains no '%'.  Stop.
...
[ 36%] Building CXX object src/coro_rpc/tests/CMakeFiles/coro_rpc_test.dir/test_variadic.cpp.o
gmake[1]: *** [CMakeFiles/Makefile2:1004: src/struct_pack/benchmark/CMakeFiles/struct_pack_benchmark.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
...
[ 85%] Built target coro_rpc_test
gmake: *** [Makefile:146: all] Error 2
```
At 33%, it is the similar error as before, but it still continues to compile.
When compiling to 85%, it exits.

**Comment by poor-circle** [comment]
emmm……You can try this to workaround.
```sh
cmake .. -DBUILD_EXAMPLES=OFF -DBUILD_BENCHMARK=OFF -DBUILD_UNIT_TESTS=OFF
cmake --build .
cmake --install . 
```

**Comment by poor-circle** [comment]
For you problem, Could you give me more info?
```
cmake ..  -DGENERATE_BENCHMARK_DATA=OFF -DBUILD_STRUCT_PB=OFF
make VERBOSE=1
```
then show me the log

**Comment by SPECIALTIGER-007** [comment]
> emmm……You can try this to workaround.
> 
> ```shell
> cmake .. -DBUILD_EXAMPLES=OFF -DBUILD_BENCHMARK=OFF -DBUILD_UNIT_TESTS=OFF
> cmake --build .
> cmake --install . 
> ```
I try it. The result is as follows.
```
[ 23%] Building CXX object src/struct_pb/protoc-plugin/CMakeFiles/protoc-gen-struct_pb.dir/main.cpp.o
[ 25%] Linking CXX executable ../../../output/bin/protoc-gen-struct_pb
[ 25%] Built target protoc-gen-struct_pb
src/struct_pb/conformance/CMakeFiles/conformance_test_runner.dir/build.make:73: *** target pattern contains no '%'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:160: src/struct_pb/conformance/CMakeFiles/conformance_test_runner.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**Comment by SPECIALTIGER-007** [comment]
> For you problem, Could you give me more info?
> 
> ```
> cmake ..  -DGENERATE_BENCHMARK_DATA=OFF -DBUILD_STRUCT_PB=OFF
> make VERBOSE=1
> ```
> 
> then show me the log
I try it. The result is as follows.
```
[ 85%] Linking CXX executable ../../../output/tests/struct_pack_test
cd /root/yalantinglibs/build/src/struct_pack/tests && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/struct_pack_test.dir/link.txt --verbose=1
/usr/bin/c++  -fcoroutines -O3 -DNDEBUG -fno-tree-slp-vectorize CMakeFiles/struct_pack_test.dir/test_serialize.cpp.o CMakeFiles/struct_pack_test.dir/test_compile_time_calculate.cpp.o CMakeFiles/struct_pack_test.dir/test_data_struct.cpp.o CMakeFiles/struct_pack_test.dir/test_data_struct2.cpp.o CMakeFiles/struct_pack_test.dir/test_tuplet.cpp.o CMakeFiles/struct_pack_test.dir/test_alignas.cpp.o CMakeFiles/struct_pack_test.dir/test_pragma_pack.cpp.o CMakeFiles/struct_pack_test.dir/test_pragma_pack_and_alignas_mix.cpp.o CMakeFiles/struct_pack_test.dir/test_varint.cpp.o CMakeFiles/struct_pack_test.dir/test_stream.cpp.o CMakeFiles/struct_pack_test.dir/test_compatible.cpp.o CMakeFiles/struct_pack_test.dir/main.cpp.o -o ../../../output/tests/struct_pack_test
make[2]: Leaving directory '/root/yalantinglibs/build'
[ 85%] Built target struct_pack_test
make  -f src/struct_pack/benchmark/CMakeFiles/struct_pack_benchmark.dir/build.make src/struct_pack/benchmark/CMakeFiles/struct_pack_benchmark.dir/depend
make[2]: Entering directory '/root/yalantinglibs/build'
src/struct_pack/benchmark/CMakeFiles/struct_pack_benchmark.dir/build.make:73: *** target pattern contains no '%'.  Stop.
make[2]: Leaving directory '/root/yalantinglibs/build'
make[1]: *** [CMakeFiles/Makefile2:1004: src/struct_pack/benchmark/CMakeFiles/struct_pack_benchmark.dir/all] Error 2
make[1]: Leaving directory '/root/yalantinglibs/build'
make: *** [Makefile:146: all] Error 2
```

**Comment by poor-circle** [comment]
> > emmm……You can try this to workaround.
> > ```shell
> > cmake .. -DBUILD_EXAMPLES=OFF -DBUILD_BENCHMARK=OFF -DBUILD_UNIT_TESTS=OFF

> > cmake --build .
> > cmake --install . 
> > ```
> 
> I try it. The result is as follows.
> 
> ```
> [ 23%] Building CXX object src/struct_pb/protoc-plugin/CMakeFiles/protoc-gen-struct_pb.dir/main.cpp.o
> [ 25%] Linking CXX executable ../../../output/bin/protoc-gen-struct_pb
> [ 25%] Built target protoc-gen-struct_pb
> src/struct_pb/conformance/CMakeFiles/conformance_test_runner.dir/build.make:73: *** target pattern contains no '%'.  Stop.
> gmake[1]: *** [CMakeFiles/Makefile2:160: src/struct_pb/conformance/CMakeFiles/conformance_test_runner.dir/all] Error 2
> gmake: *** [Makefile:136: all] Error 2
> ```

well……try this
```sh
cmake .. -DBUILD_EXAMPLES=OFF -DBUILD_BENCHMARK=OFF -DBUILD_UNIT_TESTS=OFF 
 -DGENERATE_BENCHMARK_DATA=OFF -DBUILD_STRUCT_PB=OFF
```

**Comment by poor-circle** [comment]
or 

> > > emmm……You can try this to workaround.
> > > ```shell
> > > cmake .. -DBUILD_EXAMPLES=OFF -DBUILD_BENCHMARK=OFF -DBUILD_UNIT_TESTS=OFF
> > > ```
> 
> > > cmake --build .
> > > cmake --install .
> > 
> > 
> > I try it. The result is as follows.
> > ```
> > [ 23%] Building CXX object src/struct_pb/protoc-plugin/CMakeFiles/protoc-gen-struct_pb.dir/main.cpp.o
> > [ 25%] Linking CXX executable ../../../output/bin/protoc-gen-struct_pb
> > [ 25%] Built target protoc-gen-struct_pb
> > src/struct_pb/conformance/CMakeFiles/conformance_test_runner.dir/build.make:73: *** target pattern contains no '%'.  Stop.
> > gmake[1]: *** [CMakeFiles/Makefile2:160: src/struct_pb/conformance/CMakeFiles/conformance_test_runner.dir/all] Error 2
> > gmake: *** [Makefile:136: all] Error 2
> > ```
> 
> well……try this
> 
> ```shell
> cmake .. -DBUILD_EXAMPLES=OFF -DBUILD_BENCHMARK=OFF -DBUILD_UNIT_TESTS=OFF 
>  -DGENERATE_BENCHMARK_DATA=OFF -DBUILD_STRUCT_PB=OFF
> ```

if still failed, just copy include/ylt.

**Comment by SPECIALTIGER-007** [comment]
> or
> 
> > > > emmm……You can try this to workaround.
> > > > ```shell
> > > > cmake .. -DBUILD_EXAMPLES=OFF -DBUILD_BENCHMARK=OFF -DBUILD_UNIT_TESTS=OFF
> > > > ```
> > 
> > 
> > > > cmake --build .
> > > > cmake --install .
> > > 
> > > 
> > > I try it. The result is as follows.
> > > ```
> > > [ 23%] Building CXX object src/struct_pb/protoc-plugin/CMakeFiles/protoc-gen-struct_pb.dir/main.cpp.o
> > > [ 25%] Linking CXX executable ../../../output/bin/protoc-gen-struct_pb
> > > [ 25%] Built target protoc-gen-struct_pb
> > > src/struct_pb/conformance/CMakeFiles/conformance_test_runner.dir/build.make:73: *** target pattern contains no '%'.  Stop.
> > > gmake[1]: *** [CMakeFiles/Makefile2:160: src/struct_pb/conformance/CMakeFiles/conformance_test_runner.dir/all] Error 2
> > > gmake: *** [Makefile:136: all] Error 2
> > > ```
> > 
> > 
> > well……try this
> > ```shell
> > cmake .. -DBUILD_EXAMPLES=OFF -DBUILD_BENCHMARK=OFF -DBUILD_UNIT_TESTS=OFF 
> >  -DGENERATE_BENCHMARK_DATA=OFF -DBUILD_STRUCT_PB=OFF
> > ```
> 
> if still failed, just copy include/ylt.

hhh thanks a lot. When i run the command `cmake .. -DBUILD_EXAMPLES=OFF -DBUILD_BENCHMARK=OFF -DBUILD_UNIT_TESTS=OFF -DGENERATE_BENCHMARK_DATA=OFF -DBUILD_STRUCT_PB=OFF`, and `cmake --build .`.
It appears nothing happen.
I know it can work by copying include/ylt, but i just want to build the example.
Now i abandoned this idea. Anyway thanks u very much!!!
By the way, do i need to close the issue?
