### ISSUE TITLE
[coro_rpc] The code style of default member initialization could be better?

### ISSUE THREAD

**Issue by SPECIALTIGER-007** [alibaba/yalantinglibs#379]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen

for example, in `include/ylt/coro_rpc/impl/coro_connection.hpp`, `class coro_connection`,the code style of default member initialization is inconsistent.
Some use `{}` to initialize, and some use `=` to initialize.  
I think maybe we should unified use `{}` to initialize.  

**Actually I am not sure which way is better.**
**It is necessily to modify?**

before:
```cpp
  coro_io::callback_awaitor<void>::awaitor_handler callback_awaitor_handler_{
      nullptr};
  async_simple::Executor *executor_;
  asio::ip::tcp::socket socket_;
  // FIXME: queue's performance can be imporved.
  std::deque<std::pair<std::string, std::string>> write_queue_;
  std::errc resp_err_;
  rpc_call_type rpc_call_type_ = non_callback;

  // if don't get any message in keep_alive_timeout_duration_, the connection
  // will be closed when enable_check_timeout_ is true.
  std::chrono::steady_clock::duration keep_alive_timeout_duration_;
  bool enable_check_timeout_ = false;
  asio::steady_timer timer_;
  std::atomic<bool> has_closed_ = false;

  QuitCallback quit_callback_ = nullptr;
  uint64_t conn_id_ = 0;
  uint64_t delay_resp_cnt = 0;
```

after:
```cpp
...

bool enable_check_timeout_ {false};

...
```

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by poor-circle** [comment]
Close by #381 merged.
