### ISSUE TITLE
C++ 表达式必须含有常量值对未初始化的子对象的访问(成员)

### ISSUE THREAD

**Issue by peerlesszhu** [alibaba/yalantinglibs#395]
![image](https://github.com/alibaba/yalantinglibs/assets/35405016/45ac0694-352a-4ade-8e63-4e0aadfa423e)
为啥我这里编译不过去 求解？

这里是配置
![image](https://github.com/alibaba/yalantinglibs/assets/35405016/4f2c343b-5b04-4996-aaf2-87569df7caab)

**Comment by qicosmos** [comment]
编译出错信息是什么呢？

**Comment by qicosmos** [comment]
看起来是智能提示不对，编译应该没问题。

**Comment by poor-circle** [comment]
MSVC 的intellisense出错了，编译应该没问题

**Comment by peerlesszhu** [comment]
确实编译没问题 谢谢楼上大佬
