### ISSUE TITLE
不支持复合结构体吗？

### ISSUE THREAD

**Issue by FakeItUtillMakeIt** [alibaba/yalantinglibs#416]
### Search before asking

- [ ] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by FakeItUtillMakeIt** [comment]
可以

**Comment by FakeItUtillMakeIt** [comment]
每个结构体都需要注册

**Comment by poor-circle** [comment]
这几个库都是可以嵌套结构体的，对于聚合类型，struct_pack不需要注册就可以序列化。

**Comment by FakeItUtillMakeIt** [comment]
struct_json，刚刚测试了一下，复合结构体里面的结构使用REFLECTION注册一下，可以使用
