### ISSUE TITLE
[struct_pack] Crossplatform support?

### ISSUE THREAD

**Issue by movqword** [alibaba/yalantinglibs#436]
Hey guys! 
First of all - thank you for pub useful stuff.

This is no issue but question, sorry for this contact method but here is no many ways.

For me very interesting if **struct_pack** will works well with different platforms and STL vendors, as example:

System 1 (Sender)
- OS: Windows (x86)
- STL vendor: Microsoft (MSVC)

System 2 (Receiver)
- OS: Linux (x64)
- STL vendor: GNU (GCC)

I will get correct data after deserialize at the end point if size_t defined different and if inner layout of STL containers not restricted?

With best regards, thank you.

**Comment by poor-circle** [comment]
Good question!
Here are some tips for cross-platform:
1. make sure `CHAR_BIT == 8`.
2. the machine should be all little-endian or big-endian. If not, struct_pack will detect the error with high probability (about `1 - 2^-16`) by md5. But if hash collision happened, the bahavior is undefined. 
3. the `wchar_t` and the type used `wchar_t` (e.g. `std::vector<wchar_t>`, `std::wstring`) is not cross-platfrom. struct_pack can't check this problem so the bahavior is undefined. But struct_pack won't enable those type without define marco `STRUCT_PACK_ENABLE_UNPORTABLE_TYPE`
4. In other case, struct_pack is cross platform. Thanks for you issue, I will add some test & document.

**Comment by poor-circle** [comment]
For your case, there is no any problem if you don't use wchar_t.

**Comment by movqword** [comment]
Thank you for response!

Importance of endianness nice tip, i will take into account the information.

**Comment by poor-circle** [comment]
Oh, I forget something.
For example, `long` is 32 bit in x86 msvc, but is 64 bit in x64 msvc. struct_pack will detect the error by md5, but it's better for your data struct to use int64_t, int32_t instead of long, int when cross-platform.

**Comment by movqword** [comment]
All right, thank you!

Will be nice too see in future full compatible without binding to system / bitness / endianness, sure you know that protobuf or flatbuffer already compensate these problems, but they not concurrents to struct_pack by speed or usage comfortable.

With best regards.

**Comment by poor-circle** [comment]
> Will be nice too see in future full compatible without binding to system / bitness / endianness, sure you know that protobuf or flatbuffer already compensate these problems, but they not concurrents to struct_pack by speed or usage comfortable.
> 
> In common i see good future with struct_pack in game-dev, but hard to make point on it while i must care about end-point systems (it's can be mobile, laptop, pc and etc.).
> 
> With best regards.

Well, the problem of little-endian/big-endain convert is in my todolist.

**Comment by poor-circle** [comment]
I have add a test for cross platform, It works well when cross linux/macos/win32/win64. See #471

**Comment by poor-circle** [comment]
Now struct_pack support big-endian. So I think i can close this issue.
