### ISSUE TITLE
easylog中CRITICAL 和FATAL不等价

### ISSUE THREAD

**Issue by siriuslzx** [alibaba/yalantinglibs#438]
### What happened + What you expected to happen
文档中说CRITICAL 和FATAL 是等价的，但实际不是。把test_easylog.cpp Line92换成 ELOG(CRITICAL) << "fatal"; 就会测试失败。
因为在结束程序时，是这样判断的：
    if (record.get_severity() == Severity::CRITICAL) {
      flush();
      std::exit(EXIT_FAILURE);
    }

### Reproduction way
需要std::exit时，把Severity::FATAL加上；再把test_easylog.cpp Line92去掉

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by qicosmos** [comment]
对，这个地方需要fix 一下，需要保证他们是一致的。
