### ISSUE TITLE
[struct_pack] Use macro STRUCT_PACK_REFL_FLAG in header get duplicate symbol error

### ISSUE THREAD

**Issue by codingl2k1** [alibaba/yalantinglibs#443]
### Search before asking

- [ ] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by poor-circle** [comment]
A rookie mistake…I forget add inline keyword. I'll fix it soon
