### ISSUE TITLE
[struct_pack] Best practice for struct_pack a base pointer?

### ISSUE THREAD

**Issue by codingl2k1** [alibaba/yalantinglibs#444]
### Search before asking

- [ ] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen

```C++
class A {
  virtual ~A() {}
};

class B: public A {
};

A *a = new B();
// How to struct pack/unpack a? Should I define a virtual function and implement them in each subtype with struct_pack?
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by poor-circle** [comment]
Well, struct_pack don't provide ability for RTTI/runtime reflection, it's very hard in non-intrusive design.

Of course, you can define a virtual function and implement them in each subtype with struct_pack.
You can also use a CRTP helper class to add a virtual serialize/deserialize interface.
```cpp
template<typename Parent, typename Child>
struct struct_pack_serializble_helper: public Parent {
  virtual std::string serialize() override {
     return struct_pack::serialize<std::string>(*(Child*)this);;
  }
  virtual ~struct_pack_serializble_helper()=0;
};

struct A {
  virtual ~A(){}
  virtual std::string serialize()=0;
};

struct B: public struct_pack_serializble_helper<A , B> {
    ~B(){};
};
```

**Comment by codingl2k1** [comment]
> Well, struct_pack don't provide ability for RTTI/runtime reflection, it's very hard in non-intrusive design.
> 
> Of course, you can define a virtual function and implement them in each subtype with struct_pack. You can also use a CRTP helper class to add a virtual serialize/deserialize interface.
> 
> ```c++
> template<typename Parent, typename Child>
> struct struct_pack_serializble_helper: public Parent {
>   virtual std::string serialize() override {
>      return struct_pack::serialize<std::string>(*(Child*)this);;
>   }
>   virtual ~struct_pack_serializble_helper()=0;
> };
> 
> struct A {
>   virtual ~A(){}
>   virtual std::string serialize()=0;
> };
> 
> struct B: public struct_pack_serializble_helper<A , B> {
>     ~B(){};
> };
> ```

But, how to deserialize?

**Comment by poor-circle** [comment]
Well, that is classic problem for C++. We need a factory mode. I will provide some helper class for it soon.

**Comment by codingl2k1** [comment]
> Well, that is classic problem for C++. We need a factory mode. I will provide some helper class for it soon.

Got it. Thanks.

**Comment by poor-circle** [comment]
```cpp
template<typename Parent, typename Child>
struct struct_pack_serializble_helper: public Parent {
  virtual std::string serialize() override {
     std::string ret;
     ret.push_back((Child*)this->get_id());
     struct_pack::serialize_to(ret, *(Child*)this);
     return ret;
  }
  virtual ~struct_pack_serializble_helper()=0;
};

struct Base {
  virtual ~A(){}
  virtual std::string serialize()=0;
  static std::unique_ptr<Base> deserialize(std::string_view sv) {
    std::unique_ptr<Base> base=nullptr;
    if (sv.empty())
        return base;
    uint8_t id=sv[0];
    sv=sv.substr(1);
    switch (id) {
       case 0:
         base=std::make_unique<foo>();
         struct_pack::deserialize_to<foo>(*(foo*)base);
         break;
       case 1:
         base=std::make_unique<Bar>();
         struct_pack::deserialize_to<bar>(*(bar*)base);
       default:
    }
    return base;
  }
};

struct foo: public struct_pack_serializble_helper<Base , foo> {
    uint8_t get_id() {return 0;}
    ~B(){};
};

struct bar: public struct_pack_serializble_helper<Base , bar> {
    uint8_t get_id() {return 0;}
    ~B(){};
};
```

**Comment by poor-circle** [comment]
> > 
> 
> Cool. As `foo` and `bar` are different types, why `0` and `1` are required?

It used for record the type of serialize object.

**Comment by codingl2k1** [comment]
> > > 
> > 
> > 
> > Cool. As `foo` and `bar` are different types, why `0` and `1` are required?
> 
> It used for record the type of serialize object.

Is it possible to use type hash as the key?

**Comment by poor-circle** [comment]
> > > > 
> > > 
> > > 
> > > Cool. As `foo` and `bar` are different types, why `0` and `1` are required?
> > 
> > 
> > It used for record the type of serialize object.
> 
> Is it possible to use type hash as the key?

the struct_pack type system is different with C++ type system.
For example:
```cpp
struct foo {
  std::vector<int> a;
};
struct bar {
  std::deque<int> a;
};
```
They have same type hash code.

**Comment by poor-circle** [comment]
But your idea inspire me.
Maybe struct_pack can check if the type is derived from `struct_pack_serializble_helper` and in this case calculate the MD5 with the type & ID. 
Then I can add a helper function like:
```
std::unique_ptr<Base> base = struct_pack::deserialize_derived<foo,bar>(sv);
```
And the user just need write those codes:

```cpp
struct Base {
  virtual ~Base(){}
  virtual std::string serialize()=0;
  static std::unique_ptr<Base> deserialize(std::string_view sv) {
    return struct_pack::deserialize_derived<foo,bar>(sv);;
  }
};
struct foo: public struct_pack_serializble_helper<Base , foo, 0> {
    //...
    ~foo(){};
};

struct bar: public struct_pack_serializble_helper<Base , bar, 1> {
    //...
    ~bar(){};
};
```

**Comment by poor-circle** [comment]
Thanks for your suggestion. I will add this to my todolist.

**Comment by codingl2k1** [comment]
> But your idea inspire me. Maybe struct_pack can check if the type is derived from `struct_pack_serializble_helper` and in this case calculate the MD5 with the type & ID. Then I can add a helper function like:
> 
> ```
> std::unique_ptr<Base> base = struct_pack::deserialize_derived<foo,bar>(sv);
> ```
> 
> And the user just need write those codes:
> 
> ```c++
> struct Base {
>   virtual ~Base(){}
>   virtual std::string serialize()=0;
>   static std::unique_ptr<Base> deserialize(std::string_view sv) {
>     return struct_pack::deserialize_derived<foo,bar>(sv);;
>   }
> };
> struct foo: public struct_pack_serializble_helper<Base , foo, 0> {
>     //...
>     ~foo(){};
> };
> 
> struct bar: public struct_pack_serializble_helper<Base , bar, 1> {
>     //...
>     ~bar(){};
> };
> ```

Hope the helper without 0, 1, ... But, I am not sure if there exists a suitable type hash.

```C++
struct Base {
  virtual ~Base(){}
  virtual std::string serialize()=0;
  static std::unique_ptr<Base> deserialize(std::string_view sv) {
    return struct_pack::deserialize_derived<foo,bar>(sv);;
  }
};
struct foo: public struct_pack_serializble_helper<Base , foo> {
    //...
    ~foo(){};
};

struct bar: public struct_pack_serializble_helper<Base , bar> {
    //...
    ~bar(){};
};
```

**Comment by poor-circle** [comment]
> 

Well, maybe we can add a default template argument for the ID when all the type has different type hash. struct_pack can check it in compile time. The ID is required only if there has two same type or hash collision happened.

**Comment by codingl2k1** [comment]
> But your idea inspire me. Maybe struct_pack can check if the type is derived from `struct_pack_serializble_helper` and in this case calculate the MD5 with the type & ID. Then I can add a helper function like:
> 
> ```
> std::unique_ptr<Base> base = struct_pack::deserialize_derived<foo,bar>(sv);
> ```
> 
> And the user just need write those codes:
> 
> ```c++
> struct Base {
>   virtual ~Base(){}
>   virtual std::string serialize()=0;
>   static std::unique_ptr<Base> deserialize(std::string_view sv) {
>     return struct_pack::deserialize_derived<foo,bar>(sv);;
>   }
> };
> struct foo: public struct_pack_serializble_helper<Base , foo, 0> {
>     //...
>     ~foo(){};
> };
> 
> struct bar: public struct_pack_serializble_helper<Base , bar, 1> {
>     //...
>     ~bar(){};
> };
> ```

The `struct_pack_serializble_helper` is not compatible with containers. e.g.

```C++
std::vector<std::shared_ptr<Base>> vec;
auto serialized = struct_pack::serialize<std::string>(vec);
```

**Comment by poor-circle** [comment]
> > But your idea inspire me. Maybe struct_pack can check if the type is derived from `struct_pack_serializble_helper` and in this case calculate the MD5 with the type & ID. Then I can add a helper function like:
> > ```
> > std::unique_ptr<Base> base = struct_pack::deserialize_derived<foo,bar>(sv);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And the user just need write those codes:
> > ```c++
> > struct Base {
> >   virtual ~Base(){}
> >   virtual std::string serialize()=0;
> >   static std::unique_ptr<Base> deserialize(std::string_view sv) {
> >     return struct_pack::deserialize_derived<foo,bar>(sv);;
> >   }
> > };
> > struct foo: public struct_pack_serializble_helper<Base , foo, 0> {
> >     //...
> >     ~foo(){};
> > };
> > 
> > struct bar: public struct_pack_serializble_helper<Base , bar, 1> {
> >     //...
> >     ~bar(){};
> > };
> > ```
> 
> The `struct_pack_serializble_helper` is not compatible with containers. e.g.
> 
> ```c++
> std::vector<std::shared_ptr<Base>> vec;
> auto serialized = struct_pack::serialize<std::string>(vec);
> ```

Well, the problem is struct_pack don't support user-defined serialize/deserialize now.
We can detact if struct has member function serialize/deserialize then use user-defined function instead of default serialization.

**Comment by poor-circle** [comment]
By the way, struct_pack don't support shared_ptr too now.

**Comment by codingl2k1** [comment]
> > > But your idea inspire me. Maybe struct_pack can check if the type is derived from `struct_pack_serializble_helper` and in this case calculate the MD5 with the type & ID. Then I can add a helper function like:
> > > ```
> > > std::unique_ptr<Base> base = struct_pack::deserialize_derived<foo,bar>(sv);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And the user just need write those codes:
> > > ```c++
> > > struct Base {
> > >   virtual ~Base(){}
> > >   virtual std::string serialize()=0;
> > >   static std::unique_ptr<Base> deserialize(std::string_view sv) {
> > >     return struct_pack::deserialize_derived<foo,bar>(sv);;
> > >   }
> > > };
> > > struct foo: public struct_pack_serializble_helper<Base , foo, 0> {
> > >     //...
> > >     ~foo(){};
> > > };
> > > 
> > > struct bar: public struct_pack_serializble_helper<Base , bar, 1> {
> > >     //...
> > >     ~bar(){};
> > > };
> > > ```
> > 
> > 
> > The `struct_pack_serializble_helper` is not compatible with containers. e.g.
> > ```c++
> > std::vector<std::shared_ptr<Base>> vec;
> > auto serialized = struct_pack::serialize<std::string>(vec);
> > ```
> 
> Well, the problem is struct_pack don't support user-defined serialize/deserialize now. We can detact if struct has member function serialize/deserialize then use user-defined function instead of default serialization.

Do you have plans for supporting user-defined serialization?

**Comment by poor-circle** [comment]
I'll try to support it later.

**Comment by poor-circle** [comment]
The least job is support user-defined serialization & deserialization & add a CRTP helper class to simply code

**Comment by poor-circle** [comment]
OK. The prev solution is only work when deserialize a polymorphic root type. The new solution take it as a normal struct_pack type so it can work in more situations. 
I add base pointer into struct_pack type system. Here is the new example:
```cpp
// base.h
struct base {
  virtual uint32_t get_struct_pack_id() const = 0;
  virtual ~base(){};
};
// derived1.h
struct derived1 : public base {
  virtual uint32_t get_struct_pack_id() const;
  int a = 2;
};
STRUCT_PACK_REFL(derived1, a);
// derived2.h
struct derived2 : public base {
  virtual uint32_t get_struct_pack_id() const;
  std::string b = "Hello";
};
STRUCT_PACK_REFL(derived2, b);

//test.cpp
#include "base.h"
#include "derived1.h"
#include "dervied2.h"
STRUCT_PACK_DERIVED_DECL(base, derived1, derived2);

int test(std::vector<std::unique_ptr<base>>) {
  std::vector<std::unique_ptr<base>> vec;
  vec.emplace_back(std::make_unique<derived2>());
  vec.emplace_back(std::make_unique<derived1>());

  auto buffer=struct_pack::serialize(vec);
  auto ret = struct_pack::deserialize(buffer);
}


```
