### ISSUE TITLE
[struct_pack] Is copy constructor required for deserializing?

### ISSUE THREAD

**Issue by codingl2k1** [alibaba/yalantinglibs#445]
### Search before asking

- [ ] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen

I got a compile error when deserializing a type with copy constructor removed:

> struct_pack.hpp:347:10: error: call to implicitly-deleted copy constructor of  ....

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by poor-circle** [comment]
```cpp
struct_pack::deserialize<T>(...);// need default constructor
struct_pack::deserialize_to(t,...);// don't need default constructor
```
copy constructor is not requried for deserializing. Maybe you can give me a example.

**Comment by codingl2k1** [comment]
> ```c++
> struct_pack::deserialize<T>(...);// need default constructor
> struct_pack::deserialize_to(t,...);// don't need default constructor
> ```
> 
> copy constructor is not required for deserializing. Maybe you can give me a example.

```C++
class A {
public:
  A() = default;
  A(const A &) = delete;
  void operator=(const A &) = delete;

  int i;
};

STRUCT_PACK_REFL(A, i);

int main() {
  auto a = A();
  a.i = 5;
  auto s = struct_pack::serialize(a);
  auto b = struct_pack::deserialize<A>(s);
  return 0;
}
```

Compile failed
```bash
bazel-out/darwin_arm64-opt/bin/_virtual_includes/struct_pack/struct_pack.hpp:347:10: error: call to implicitly-deleted copy constructor of 'expected<detail::get_args_type<A>, struct_pack::errc>' (aka 'expected<A, struct_pack::errc>')
  return ret;
         ^~~
cpp/src/actor_class_test.cc:32:25: note: in instantiation of function template specialization 'struct_pack::deserialize<A, std::vector<char>>' requested here
  auto b = struct_pack::deserialize<A>(s);
                        ^
bazel-out/darwin_arm64-opt/bin/_virtual_includes/struct_pack/util/expected.hpp:1542:13: note: explicitly defaulted function was implicitly deleted here
  constexpr expected(const expected &rhs) = default;
            ^
bazel-out/darwin_arm64-opt/bin/_virtual_includes/struct_pack/util/expected.hpp:1287:18: note: copy constructor of 'expected<A, struct_pack::errc>' is implicitly deleted because base class 'detail::expected_delete_ctor_base<A, errc>' has a deleted copy constructor
                 private detail::expected_delete_ctor_base<T, E>,
                 ^
bazel-out/darwin_arm64-opt/bin/_virtual_includes/struct_pack/util/expected.hpp:1150:3: note: 'expected_delete_ctor_base' has been explicitly marked deleted here
  expected_delete_ctor_base(const expected_delete_ctor_base &) = delete;
  ^
1 error generated.
```
Compiler: `Apple clang version 14.0.3 (clang-1403.0.22.14.1)`

**Comment by poor-circle** [comment]
> > ```c++
> > struct_pack::deserialize<T>(...);// need default constructor
> > struct_pack::deserialize_to(t,...);// don't need default constructor
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > copy constructor is not required for deserializing. Maybe you can give me a example.
> 
> ```c++
> class A {
> public:
>   A() = default;
>   A(const A &) = delete;
>   void operator=(const A &) = delete;
> 
>   int i;
> };
> 
> STRUCT_PACK_REFL(A, i);
> 
> int main() {
>   auto a = A();
>   a.i = 5;
>   auto s = struct_pack::serialize(a);
>   auto b = struct_pack::deserialize<A>(s);
>   return 0;
> }
> ```
> 
> Compile failed
> 
> ```shell
> bazel-out/darwin_arm64-opt/bin/_virtual_includes/struct_pack/struct_pack.hpp:347:10: error: call to implicitly-deleted copy constructor of 'expected<detail::get_args_type<A>, struct_pack::errc>' (aka 'expected<A, struct_pack::errc>')
>   return ret;
>          ^~~
> cpp/src/actor_class_test.cc:32:25: note: in instantiation of function template specialization 'struct_pack::deserialize<A, std::vector<char>>' requested here
>   auto b = struct_pack::deserialize<A>(s);
>                         ^
> bazel-out/darwin_arm64-opt/bin/_virtual_includes/struct_pack/util/expected.hpp:1542:13: note: explicitly defaulted function was implicitly deleted here
>   constexpr expected(const expected &rhs) = default;
>             ^
> bazel-out/darwin_arm64-opt/bin/_virtual_includes/struct_pack/util/expected.hpp:1287:18: note: copy constructor of 'expected<A, struct_pack::errc>' is implicitly deleted because base class 'detail::expected_delete_ctor_base<A, errc>' has a deleted copy constructor
>                  private detail::expected_delete_ctor_base<T, E>,
>                  ^
> bazel-out/darwin_arm64-opt/bin/_virtual_includes/struct_pack/util/expected.hpp:1150:3: note: 'expected_delete_ctor_base' has been explicitly marked deleted here
>   expected_delete_ctor_base(const expected_delete_ctor_base &) = delete;
>   ^
> 1 error generated.
> ```
> 
> Compiler: `Apple clang version 14.0.3 (clang-1403.0.22.14.1)`

Ok, in this case you need use `struct_pack::deserialize_to()`

**Comment by poor-circle** [comment]
```cpp
class A {
public:
  A() = default;
  A(const A &) = delete;
  void operator=(const A &) = delete;

  int i;
};

STRUCT_PACK_REFL(A, i);

int main() {
  auto a = A();
  a.i = 5;
  auto s = struct_pack::serialize(a);
  auto a2=A();
  auto b = struct_pack::deserialize_to(a2, s);
  return 0;
}
```

**Comment by codingl2k1** [comment]
> 

Got it. `deserialize` requires a public default constructor and a copy / move constructor.
