### ISSUE TITLE
how to struct pack a class with pointer and union

### ISSUE THREAD

**Issue by ahao1995** [alibaba/yalantinglibs#447]
example:
```
class Test {
public:
  int usr1;
};
class Test1 {
public:
  int usr2;
  union {
    double call;
    double put;
  };
  const Test *test;
};
```
like this, there is a union and a pointer in class, how to struct pack it

**Comment by poor-circle** [comment]
struct_pack don't support union because it's unsafe & c++ type traits cannot get the type contained in union for type check.
You can use std::variant to instead of union. It's type safe.

**Comment by poor-circle** [comment]
struct_pack don't support raw pointer because user may forget free the pointer.
You can use std::unique_ptr to instead it.

**Comment by poor-circle** [comment]
You can change your struct like:
```
class Test {
public:
  int usr1;
};
class Test1 {
public:
  int usr2;
  std::variant<double,float> data;
  std::unique_ptr<Test> test;
};
```

**Comment by ahao1995** [comment]
The struct is from third libs, so I can not change it, I think pointer may need a deep copy. In old cpp, raw pointer is more common

**Comment by poor-circle** [comment]
You have two solution.
1. copy Test1 to your struct. 
2. Add a wrapper for Test1

**Comment by poor-circle** [comment]
Here is the second solutions wrapper:
```cpp
class Test2Wrapper {
 private:
  std::unique_ptr<Test> test_ptr_wrapper;

 public:
  Test1 &impl;
  Test2Wrapper(Test1 &impl) : impl(impl), test_ptr_wrapper((Test *)impl.test) {}
  int &usr2() { return impl.usr2; }
  const int &usr2() const { return impl.usr2; }
  double &call() { return impl.call; }
  const double &call() const { return impl.call; }
  std::unique_ptr<Test> &test() {
    [[maybe_unused]] auto ptr = test_ptr_wrapper.release();
    return test_ptr_wrapper;
  }
  const std::unique_ptr<Test> &test() const { return test_ptr_wrapper; }
  ~Test2Wrapper() { impl.test = test_ptr_wrapper.release(); }
};
STRUCT_PACK_REFL(Test2Wrapper, usr2(), call(), test())

int main() {
  Test1 t1, t2;
  t1.usr2 = 1;
  t1.call = 3.14;
  auto t = new Test();
  t->usr1 = 3;
  t1.test = t;

  {
    Test2Wrapper wrapper1{t1}, wrapper2{t2};
    auto buffer = struct_pack::serialize(wrapper1);
    auto ec = struct_pack::deserialize_to(wrapper2, buffer);
    assert(ec==struct_pack::errc::ok);
  }
  assert(t1.test->usr1 == t2.test->usr1);
  assert(t1.call == t2.call);
  assert(t1.usr2 == t2.usr2);

  delete t1.test;
  delete t2.test;
}
```

**Comment by ahao1995** [comment]
> Here is the second solution's wrapper:
> 
> ```c++
> class Test2Wrapper {
>  private:
>   std::unique_ptr<Test> test_ptr_wrapper;
> 
>  public:
>   Test1 &impl;
>   Test2Wrapper(Test1 &impl) : impl(impl), test_ptr_wrapper((Test *)impl.test) {}
>   int &usr2() { return impl.usr2; }
>   const int &usr2() const { return impl.usr2; }
>   double &call() { return impl.call; }
>   const double &call() const { return impl.call; }
>   std::unique_ptr<Test> &test() {
>     [[maybe_unused]] auto ptr = test_ptr_wrapper.release();
>     return test_ptr_wrapper;
>   }
>   const std::unique_ptr<Test> &test() const { return test_ptr_wrapper; }
>   ~Test2Wrapper() { impl.test = test_ptr_wrapper.release(); }
> };
> STRUCT_PACK_REFL(Test2Wrapper, usr2(), call(), test())
> 
> int main() {
>   Test1 t1, t2;
>   t1.usr2 = 1;
>   t1.call = 3.14;
>   auto t = new Test();
>   t->usr1 = 3;
>   t1.test = t;
> 
>   {
>     Test2Wrapper wrapper1{t1}, wrapper2{t2};
>     auto buffer = struct_pack::serialize(wrapper1);
>     auto ec = struct_pack::deserialize_to(wrapper2, buffer);
>     assert(ec==struct_pack::errc::ok);
>   }
>   assert(t1.test->usr1 == t2.test->usr1);
>   assert(t1.call == t2.call);
>   assert(t1.usr2 == t2.usr2);
> 
>   delete t1.test;
>   delete t2.test;
> }
> ```

thanks~~~
