### ISSUE TITLE
[struct_pack] Bitfield support

### ISSUE THREAD

**Issue by movqword** [alibaba/yalantinglibs#465]
Hey guys!

I just found that struct_pack can't handle one usefull trick for less memory usage - bitfield.

**Example with game item object:**

With bitfields will be just **4** bytes (without alignment - 30 bits):
```C++
struct Item {
  uint32_t Slot : 8;
  uint32_t Id : 14;
  uint32_t Level : 4;
  uint32_t Option1 : 1;
  uint32_t Option2 : 1;
  uint32_t Option3 : 1;
  uint32_t Option4 : 1;
};
```

Without bitfields will be **10** bytes (without alignment - 72 bits):
```C++
struct Item {
  uint8_t Slot;
  uint16_t Id;
  uint8_t Level;
  uint8_t Option1;
  uint8_t Option2;
  uint8_t Option3;
  uint8_t Option4;
};
```

Of course i understand that this is very specific feature, but maybe any chance to include it in todo list?

**Comment by poor-circle** [comment]
Here is a workaround:
```cpp
#include<cstdint>
struct Item {
  uint32_t Slot : 8;
  uint32_t Id : 14;
  uint32_t Level : 4;
  uint32_t Option1 : 1;
  uint32_t Option2 : 1;
  uint32_t Option3 : 1;
  uint32_t Option4 : 1;
};

using wrapper_t=char[sizeof(Item)];
void serialize(const Item& item) {
    auto &wrapper=*(wrapper_t*)&item;
    struct_pack::serialize(wrapper);
}
```

**Comment by poor-circle** [comment]
Another better workaround. I believe that is what you want.
```cpp
struct Item {
  uint32_t Slot : 8;
  uint32_t Id : 14;
  uint32_t Level : 4;
  uint32_t Option1 : 1;
  uint32_t Option2 : 1;
  uint32_t Option3 : 1;
  uint32_t Option4 : 1;
  auto& value();
  const auto& value() const;
};
using wrapper_t=char[sizeof(Item)];
auto& Item::value() { return *(wrapper_t*)this; }
const auto& Item::value() const { return *(const wrapper_t*)this; }
STRUCT_PACK_REFL(Item, value());
auto test() {
  Item it{};
  it.Slot = 1;
  it.Id = 14;
  it.Option3 = 1;
  auto buffer = struct_pack::serialize(it);
  auto res = struct_pack::deserialize<Item>(buffer);
  auto &it2 = res.value();
  assert(it2.Id == it.Id);
  assert(it2.Slot == it.Slot);
  assert(it2.Option3 == it.Option3);
}
```

Make sure your code in only work in little-endian.

**Comment by poor-circle** [comment]
I afraid the bitfield is hard for cross-platform. Make sure you only use it in the same endian.

**Comment by poor-circle** [comment]
For native support, during c++ don't have enough type traits util for bitfield, user have write some boiled code.
Maybe we can support it as:
```cpp
struct Item {
  uint32_t Slot : 8;
  uint32_t Id : 14;
  uint32_t Level : 4;
  uint32_t Option1 : 1;
  uint32_t Option2 : 1;
  uint32_t Option3 : 1;
  uint32_t Option4 : 1;
};
void struct_pack_bitfield_decl(Item);
//OR: STRUCT_PACK_BITFIELD_DECL(Item);
```
But remember, bitfield is not cross-platform. There has no type check for each field. It can't work in opposite endian. It may have some problem when cross different platform/compiler.

**Comment by poor-circle** [comment]
Furthermore, a cross-platform way is to use std::bitset

**Comment by movqword** [comment]
> Furthermore, a cross-platform way is to use std::bitset

All right, but seems it's cant resolve common target - compact size, as example:
```C++
struct Item {
  std::bitset<8> Slot;
  std::bitset<14> Id;
  std::bitset<4> Level;
  std::bitset<1> Option1;
  std::bitset<1> Option2;
  std::bitset<1> Option3;
  std::bitset<1> Option4;
};
```

Will be 28 bytes. Can't check which size will be after serialization becouse struct_pack invokes C1001 in reflection.hpp:
<img width="656" alt="image" src="https://github.com/alibaba/yalantinglibs/assets/13312509/19d2527a-8d4c-44d2-a86a-9c2d3419eb7e">

**Comment by poor-circle** [comment]
> > Furthermore, a cross-platform way is to use std::bitset
> 
> All right, but seems it's cant resolve common target - compact size, as example:
> 
> ```c++
> struct Item {
>   std::bitset<8> Slot;
>   std::bitset<14> Id;
>   std::bitset<4> Level;
>   std::bitset<1> Option1;
>   std::bitset<1> Option2;
>   std::bitset<1> Option3;
>   std::bitset<1> Option4;
> };
> ```
> 
> Will be 28 bytes. Can't check which size will be after serialization becouse struct_pack invokes C1001 in reflection.hpp: <img alt="image" width="656" src="https://user-images.githubusercontent.com/13312509/270175331-19d2527a-8d4c-44d2-a86a-9c2d3419eb7e.png">

I mean:
```cpp
struct Item {
  std::bitset<32> data;
  uint8_t getSlot();
  void setSlot(uint8_t);
  uint16_t getID();
  void setID(uint16_t);
  //.....
};
```

**Comment by poor-circle** [comment]
> Here is a workaround. I believe that is what you want.
> 
> ```c++
> struct Item {
>   uint32_t Slot : 8;
>   uint32_t Id : 14;
>   uint32_t Level : 4;
>   uint32_t Option1 : 1;
>   uint32_t Option2 : 1;
>   uint32_t Option3 : 1;
>   uint32_t Option4 : 1;
>   auto& value();
>   const auto& value() const;
> };
> using wrapper_t=char[sizeof(Item)];
> auto& Item::value() { return *(wrapper_t*)this; }
> const auto& Item::value() const { return *(const wrapper_t*)this; }
> STRUCT_PACK_REFL(Item, value());
> // reflect Item as a char[4] in struct_pack type system.
> auto test() {
>   Item it{};
>   it.Slot = 1;
>   it.Id = 14;
>   it.Option3 = 1;
>   auto buffer = struct_pack::serialize(it);
>   auto res = struct_pack::deserialize<Item>(buffer);
>   auto &it2 = res.value();
>   assert(it2.Id == it.Id);
>   assert(it2.Slot == it.Slot);
>   assert(it2.Option3 == it.Option3);
> }
> ```

If you don't care for cross-platform, that is the workaround.

**Comment by movqword** [comment]
> Will be 28 bytes. Can't check which size will be after serialization becouse struct_pack invokes C1001 in reflection.hpp:



> > > Furthermore, a cross-platform way is to use std::bitset
> > 
> > 
> > All right, but seems it's cant resolve common target - compact size, as example:
> > ```c++
> > struct Item {
> >   std::bitset<8> Slot;
> >   std::bitset<14> Id;
> >   std::bitset<4> Level;
> >   std::bitset<1> Option1;
> >   std::bitset<1> Option2;
> >   std::bitset<1> Option3;
> >   std::bitset<1> Option4;
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Will be 28 bytes. Can't check which size will be after serialization becouse struct_pack invokes C1001 in reflection.hpp: <img alt="image" width="656" src="https://user-images.githubusercontent.com/13312509/270175331-19d2527a-8d4c-44d2-a86a-9c2d3419eb7e.png">
> 
> I mean:
> 
> ```c++
> struct Item {
>   std::bitset<32> data;
>   uint8_t getSlot();
>   void setSlot(uint8_t);
>   uint16_t getID();
>   void setID(uint16_t);
>   //.....
> };
> ```
> 
> You need to write the store rule manually, but it's only way for cross-platform.

Oh, now get it, thank you!
