### ISSUE TITLE
Can coro_rpc handle RPC requests in a batched manner?

### ISSUE THREAD

**Issue by ttbachyinsda** [alibaba/yalantinglibs#473]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen

For example, 10000 RPC calls are made every 1 second, and a resident thread in the background processes a batch of RPC calls (e.g., 10) simultaneously and returns the results. This is very useful in scenarios where batching can improve performance, such as vector multiplication.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by qicosmos** [comment]
coro_rpc not support batch request similar with http1.1 pipeline now, but you can call multiple rpc requests simultaneous with async_simple::coro::collectAll to avoid wait one after another.

We will support batch request similar with http1.1 pipeline in future.

**Comment by ttbachyinsda** [comment]
Thank you for your response. The problem I am encountering is that I need to implement the producer-consumer model similar to Go channel functionality, such as:
When the service receives a request, it adds the request to a thread-safe queue.
A background thread retrieves elements from the queue and processes them.
After processing is completed, the result is sent back to the coroutine through a channel and returned to the client.
A possible implementation is through a lock, but is there a better approach using coroutines? Thank you.

**Comment by qicosmos** [comment]
I think you just need a thread pool, look at this example:
https://github.com/alibaba/yalantinglibs/blob/main/src/coro_rpc/examples/base_examples/rpc_service.cpp#L44

i think you can put the business logic in a thread pool, after the business logic finished, response to client.
