### ISSUE TITLE
Reduce the size of resp_data

### ISSUE THREAD

**Issue by lichray** [alibaba/yalantinglibs#478]
### What happened + What you expected to happen

I expect `sizeof(resp_data)` to be smaller than or equal to 64 bytes. It's larger than that when `BENCHMARK_TEST` is defined.

### Reproduction way

https://godbolt.org/z/ooWhh44Ma

### Anything else

Consider taking more advantage of the alignment by reordering the members:

```cpp
struct resp_data {
  std::error_code net_err;
  int status = 0;
  bool eof = false;
  std::string_view resp_body;
  std::span<http_header> resp_headers;
#ifdef BENCHMARK_TEST
  uint64_t total = 0;
#endif
};
```

I added default member initializers to make code like

```cpp
resp_data result;
```

as safe as

```cpp
resp_data result{};
```

### Are you willing to submit a PR?

No.

**Comment by qicosmos** [comment]
reordering the members looks better, will try it later.

**Comment by poor-circle** [comment]
Close as completed.
