### ISSUE TITLE
Optimize initial compilation warning prompts

### ISSUE THREAD

**Issue by ouliuquan** [alibaba/yalantinglibs#480]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.
![屏幕截图 2023-10-27 154846](https://github.com/alibaba/yalantinglibs/assets/38776890/26ac43d2-6042-456d-8d03-da9c47c4e5d9)

The initial compilation should not give people a wrong feeling. Although it can be compiled in the end, try to use green or ordinary information to express the missing libprotoc information.

初始编译不应该给人一种错误的感觉，虽然最后是可以编译的，但是尽量使用绿色或者普通信息的方式表达缺失libprotoc的信息
### What happened + What you expected to happen

friendly reminder
友好的提示
### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by qicosmos** [comment]
fixed in this PR: https://github.com/alibaba/yalantinglibs/pull/483
