### ISSUE TITLE
[esaylog] 输出到文件时路径问题

### ISSUE THREAD

**Issue by Zsm-amere** [alibaba/yalantinglibs#495]
### What happened + What you expected to happen
我设置了日志存储路径在运行目录下的Log文件夹，当单个文件达到 `max_file_size` 时，旧的日志文件会被移动到当前运行目录下，而不是在Log文件夹内

**Comment by qicosmos** [comment]
谢谢报告，因为是创建新文件的时候没有把设置的路径带上，稍后修复。
