### ISSUE TITLE
ELOGFMT_IMPL0 宏会重定义

### ISSUE THREAD

**Issue by QuantRokkie** [alibaba/yalantinglibs#497]
#if __has_include(<fmt/format.h>)
#define ELOGFMT_IMPL(severity, Id, ...) \
  ELOGFMT_IMPL0(severity, Id, fmt, __VA_ARGS__)
#endif

#if __has_include(<format>)
#define ELOGFMT_IMPL(severity, Id, ...) \
  ELOGFMT_IMPL0(severity, Id, std, __VA_ARGS__)
#endif

两个头文件都有的情况下, 会重复定义

**Comment by qicosmos** [comment]
这个实际会发生吗，你使用std::format 又同时使用fmt吗？

**Comment by QuantRokkie** [comment]
是的, 之前用的都是fmt,项目升级到C++20后才开始部分模块用了std::format

**Comment by qicosmos** [comment]
OK， 最近fix一下。

**Comment by qicosmos** [comment]
能用pr #498 里面的代码验证一下，我现在还没有二者都有的环境，如果还有问题我再准备一个环境测一下。@QuantRokkie

**Comment by QuantRokkie** [comment]
> 能用pr #498 里面的代码验证一下吗？我现在还没有二者都有的环境，如果还有问题我再准备一个环境测一下。@QuantRokkie

试过没有问题了
