### ISSUE TITLE
easylog 为什么要依赖到cinatra？

### ISSUE THREAD

**Issue by qljsky** [alibaba/yalantinglibs#507]
easylog新的代码time_util.h 内与cinatra产生了依赖关系，相互之间隔离开不是更好吗

**Comment by qicosmos** [comment]
里面用到了一个高性能的时间组件，它是cinatra提供的，cinatra本来就是yalantinglibs所依赖的，这个时间组件也是cinatra里面的一个独立的文件。依赖这个引起什么问题了吗？

**Comment by qljsky** [comment]
因为只准备接入easylog的情况下，在visual studio2022下编译引起cinatra http相关的报错，所以我又切回spdlog了.前一段时间测试easylog的时候没有这个问题,我个人感觉能独立一些更好些

**Comment by qicosmos** [comment]
或者把那个文件拷贝一份出来放到easylog里，保持独立性也行，我看一下怎么处理。
