### ISSUE TITLE
test_derived.cpp

### ISSUE THREAD

**Issue by kcj3054** [alibaba/yalantinglibs#511]
I confirmed that in the type of deserialize_derived_class in test_derived.cpp, the first argument is parent and the second argument is child, but I am very curious why Base and Base are used twice in the example!

struct_pack::expected<std::unique_ptr<Base>, struct_pack::errc>
Base::deserialize(std::string_view sv) {
  return struct_pack::deserialize_derived_class<Base, Base, bar, foo, gua, foo2,
                                                foo4>(sv);
}

**Comment by kcj3054** [comment]
thank you!!!

**Comment by poor-circle** [comment]
Add document for derived class. See [doc:derived-class-support](https://alibaba.github.io/yalantinglibs/en/struct_pack/struct_pack_intro.html#derived-class-support)  & [code:dervied_class](https://github.com/alibaba/yalantinglibs/blob/main/src/struct_pack/examples/derived_class.cpp)

**Comment by poor-circle** [comment]
> I confirmed that in the type of deserialize_derived_class in test_derived.cpp, the first argument is parent and the second argument is child, but I am very curious why Base and Base are used twice in the example!
> 
> struct_pack::expected<std::unique_ptr, struct_pack::errc> Base::deserialize(std::string_view sv) { return struct_pack::deserialize_derived_class<Base, Base, bar, foo, gua, foo2, foo4>(sv); }

After #532 , user don't need to repeat base class twice. struct_pack will check if base class is virtual base class automatically.
