### ISSUE TITLE
question

### ISSUE THREAD

**Issue by kcj3054** [alibaba/yalantinglibs#516]
I'm always grateful for posting because I have a question.

If there is no explanation for each function in open source, can I just analyze it while debugging? Currently, in yalantinglibs, certain libraries are well documented, but the rest only contain example code, so I am raising a question.

For example, right now I am curious about whether the server is running as a ThreadPool. There is a client_pool in the project, but I am also curious about a detailed explanation of whether the server is a thread pool and how many threads it uses.

**Comment by qicosmos** [comment]
Maybe code is the document :)

**Comment by kcj3054** [comment]
thank you! In the current document, clinet pool and client connection control are mentioned, but where are the server connection settings?   When it comes to server, is there only one server solution??
