### ISSUE TITLE
struct_pack is not compatible with vs2017 c++17

### ISSUE THREAD

**Issue by romanholidaypancakes** [alibaba/yalantinglibs#523]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen

i get an error when compiling with vs2017 c++17

### Reproduction way
- test code
```C++
struct MyStruct {
    unsigned int test{};
};

int main(int argc, char* argv[]) {
    MyStruct test{};
    auto     out1 = struct_pack::serialize(test);
    auto     out2 = struct_pack::deserialize<MyStruct>(out1);
    return 0;
}

```

- compiler configuration
  - `Visual Studio 2017 (v141)`
  ![image](https://github.com/alibaba/yalantinglibs/assets/51652878/96d033c4-7b58-4bf4-b242-c91e23b196ac)
  
  - `ISO C++17 Standard (/std:c++17)`
  ![image](https://github.com/alibaba/yalantinglibs/assets/51652878/556337b5-149b-4b45-9634-96dbbb956e18)

- first time error
  ```
  1>------ Build started: Project: ConsoleApplication1, Configuration: Release x64 ------
  1>ConsoleApplication1.cpp
  1>d:\\superthirdparty\yalantinglibs\include\ylt\struct_pack\marco.h(34): warning C4067: unexpected tokens following preprocessor directive - expected a newline
  1>d:\\superthirdparty\yalantinglibs\include\ylt\struct_pack\marco.h(42): warning C4067: unexpected tokens following preprocessor directive - expected a newline
  1>d:\\superthirdparty\yalantinglibs\include\ylt\struct_pack\endian_wrapper.hpp(17): fatal error C1083: Cannot open include file: 'bit': No such file or directory
  1>Done building project "ConsoleApplication1.vcxproj" -- FAILED.
  ```

- maybe vs2017 c++17 didn't implement it and then I used a higher version of the bit header file and still got the error
  ```C++
  1>------ Build started: Project: ConsoleApplication1, Configuration: Release x64 ------
  1>ConsoleApplication1.cpp
  1>d:\\yalantinglibs\include\ylt\struct_pack\marco.h(34): warning C4067: unexpected tokens following preprocessor directive - expected a newline
  1>d:\\yalantinglibs\include\ylt\struct_pack\marco.h(42): warning C4067: unexpected tokens following preprocessor directive - expected a newline
  1>d:\\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(118): error C2825: 'T': must be a class or namespace when followed by '::'
  1>d:\\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(364): note: see reference to class template instantiation 'struct_pack::detail::get_array_element<unsigned int>' being compiled
  1>d:\\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(346): note: see reference to function template instantiation 'bool struct_pack::detail::check_if_compatible_element_exist_impl_helper<18446744073709551615,unsigned int,>(void)' being compiled
  1>d:\\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(487): note: see reference to function template instantiation 'bool struct_pack::detail::check_if_compatible_element_exist_impl<18446744073709551615,U,,0>(std::integer_sequence<unsigned __int64,0>)' being compiled
  1>d:\\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(492): note: see reference to function template instantiation 'bool struct_pack::detail::check_if_compatible_element_exist<T,18446744073709551615>(void)' being compiled
  1>        with
  1>        [
  1>            T=std::tuple<unsigned int>
  1>        ]
  1>d:\\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(671): note: see reference to variable template 'const bool exist_compatible_member<MyStruct,-1>' being compiled
  1>d:\\yalantinglibs\include\ylt\struct_pack\calculate_size.hpp(405): note: see reference to class template instantiation 'struct_pack::detail::serialize_static_config<Type>' being compiled
  1>d:\\yalantinglibs\include\ylt\struct_pack.hpp(144): note: see reference to function template instantiation 'struct_pack::serialize_buffer_size struct_pack::detail::get_serialize_runtime_info<0,MyStruct>(const MyStruct &)' being compiled
  1>d:\\yalantinglibs\include\ylt\struct_pack.hpp(205): note: see reference to function template instantiation 'void struct_pack::serialize_to<0,Buffer,MyStruct>(Writer &,const MyStruct &)' being compiled
  1>        with
  1>        [
  1>            Buffer=std::vector<char,std::allocator<char>>,
  1>            Writer=std::vector<char,std::allocator<char>>
  1>        ]
  1>d:\vs\source\repos\consoleapplication1\consoleapplication1\consoleapplication1.cpp(18): note: see reference to function template instantiation 'Buffer struct_pack::serialize<std::vector<char,std::allocator<char>>,MyStruct>(const MyStruct &)' being compiled
  1>        with
  1>        [
  1>            Buffer=std::vector<char,std::allocator<char>>
  1>        ]
  1>d:\\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(118): error C2510: 'T': left of '::' must be a class/struct/union
  1>d:\\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(118): error C2061: syntax error: identifier 'value_type'
  1>c:\program files\microsoft visual studio\2022\enterprise\vc\tools\msvc\14.16.27023\include\variant(390): error C2027: use of undefined type 'std::variant_size<_Ty>'
  1>        with
  1>        [
  1>            _Ty=unsigned int
  1>        ]
  1>c:\program files\microsoft visual studio\2022\enterprise\vc\tools\msvc\14.16.27023\include\variant(390): note: see declaration of 'std::variant_size<_Ty>'
  1>        with
  1>        [
  1>            _Ty=unsigned int
  1>        ]
  1>d:\\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(429): note: see reference to variable template 'const size_t variant_size_v<unsigned int>' being compiled
  1>c:\program files\microsoft visual studio\2022\enterprise\vc\tools\msvc\14.16.27023\include\variant(390): error C2065: 'value': undeclared identifier
  1>c:\program files\microsoft visual studio\2022\enterprise\vc\tools\msvc\14.16.27023\include\variant(390): error C2131: expression did not evaluate to a constant
  1>c:\program files\microsoft visual studio\2022\enterprise\vc\tools\msvc\14.16.27023\include\variant(390): note: a non-constant (sub-)expression was encountered
  1>Done building project "ConsoleApplication1.vcxproj" -- FAILED.
  ```

### Anything else
- the visual studio installer allows you to quickly install the vs2017 c++ toolchain.

![image](https://github.com/alibaba/yalantinglibs/assets/51652878/9b1ca52a-bf31-41fc-878f-5e78e8ef04a1)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by poor-circle** [comment]
![image](https://github.com/alibaba/yalantinglibs/assets/51276909/39c79ff4-adad-426f-8e9c-82fa63719375)

You need at least MSVC14.20(aks visual studio 2019) to compile struct_pack.

Now we don't have plan to support vs2017, because it didn't finish some c++17 feature.

**Comment by poor-circle** [comment]
Well, I think it's possible to fix the problem, I check the cpprefence and it seems that MSVC 14.29(the high version of VS2017) support almost all c++17 feature.

**Comment by poor-circle** [comment]
Well, I think it's possible to fix the problem, I check the cpprefence and it seems that the highest version of VS2017 support almost all c++17 feature.

**Comment by poor-circle** [comment]
could you try to remove 
```cpp
template <typename T>
struct get_array_element {
  using type = typename T::value_type;
};

template <typename T, std::size_t sz>
struct get_array_element<T[sz]> {
  using type = T;
};
```
and instead it by:
```cpp
template <typename T>
struct get_array_element {
  using type = remove_cvref_t<decltype(std::declval<T>()[0])>;
};
```

**Comment by poor-circle** [comment]
> could you try to remove
> 
> ```c++
> template <typename T>
> struct get_array_element {
>   using type = typename T::value_type;
> };
> 
> template <typename T, std::size_t sz>
> struct get_array_element<T[sz]> {
>   using type = T;
> };
> ```
> 
> and instead it by:
> 
> ```c++
> template <typename T>
> struct get_array_element {
>   using type = remove_cvref_t<decltype(std::declval<T>()[0])>;
> };
> ```

I have no environment of VS2017. So I no sure if it can fix all the problem.

**Comment by poor-circle** [comment]
emmm. Could you try this?
```cpp
template <typename T, typename enable = void>
struct get_array_element {
  using type = void;
};

template <typename T>
struct get_array_element<T,std::enable_if_t<array<T>>> {
  using type = typename T::value_type;
};

template <typename T, std::size_t sz>
struct get_array_element<T[sz]> {
  using type = T;
};
```

**Comment by poor-circle** [comment]
Well, fix one problem then jump aonther one. I afraid The VS2017 has a poor support for if-constexpr statment.
Try add:
```cpp
template <typename T>
struct get_varint_size<T, std::enable_if_t<is_variant_v<T>>> {
  static constexpr std::size_t size = std::variant_size_v<T>;
};
```
Then replace the code
```cpp
    else if constexpr (id == type_id::variant_t) {
      return check_if_compatible_element_exist_impl_variant<version, T, T,
                                                            ParentArgs...>(
          std::make_index_sequence<std::variant_size_v<T>>{});
    }
```
 with:
```cpp
    else if constexpr (id == type_id::variant_t) {
      return check_if_compatible_element_exist_impl_variant<version, T, T,
                                                            ParentArgs...>(
          std::make_index_sequence<get_varint_size<T>::size>{});
    }
```

**Comment by poor-circle** [comment]
> Well, fix one problem then jump aonther one. I afraid The VS2017 has a poor support for if-constexpr statment. Try add:
> 
> ```c++
> template <typename T>
> struct get_varint_size<T, std::enable_if_t<is_variant_v<T>>> {
>   static constexpr std::size_t size = std::variant_size_v<T>;
> };
> ```
> 
> Then replace the code
> 
> ```c++
>     else if constexpr (id == type_id::variant_t) {
>       return check_if_compatible_element_exist_impl_variant<version, T, T,
>                                                             ParentArgs...>(
>           std::make_index_sequence<std::variant_size_v<T>>{});
>     }
> ```
> 
> with:
> 
> ```c++
>     else if constexpr (id == type_id::variant_t) {
>       return check_if_compatible_element_exist_impl_variant<version, T, T,
>                                                             ParentArgs...>(
>           std::make_index_sequence<get_varint_size<T>::size>{});
>     }
> ```

I afraid the poor support of if-constexpr statement could cause a lot of compile errors. If the compile error still exists, It's hard to fix all if-constexpr statement.

**Comment by poor-circle** [comment]
> here are the changes i've made
> 
> ![image](https://private-user-images.githubusercontent.com/51652878/289433888-9ac585dc-4ce7-4b12-a3ae-29f670601f53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNzI5MjAsIm5iZiI6MTcwMjI3MjYyMCwicGF0aCI6Ii81MTY1Mjg3OC8yODk0MzM4ODgtOWFjNTg1ZGMtNGNlNy00YjEyLWEzYWUtMjlmNjcwNjAxZjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA1MzAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMjViODllN2FlYjQwZWU0NTIwOTQ1NjJlZmY0ZmIzNGQzYWI2ZjZjYjhlNDhhMjAyYWQ1NThiNzFhMGFjNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xvJ5pjtGn-ONxbZhx0bZA9QXXFIbOckYu2B6x6RfBeU)
> 
> ```c++
> 1>c:\program files\microsoft visual studio\2022\enterprise\vc\tools\msvc\14.16.27023\include\variant(390): error C2027: use of undefined type 'std::variant_size<_Ty>'
> 1>        with
> 1>        [
> 1>            _Ty=MyStruct
> 1>        ]
> 1>c:\program files\microsoft visual studio\2022\enterprise\vc\tools\msvc\14.16.27023\include\variant(390): note: see declaration of 'std::variant_size<_Ty>'
> 1>        with
> 1>        [
> 1>            _Ty=MyStruct
> 1>        ]
> 1>d:\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(591): note: see reference to variable template 'const size_t variant_size_v<MyStruct>' being compiled
> 1>d:\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(478): note: see reference to function template instantiation 'size_t struct_pack::detail::calculate_compatible_version_size<T,>(void)' being compiled
> 1>        with
> 1>        [
> 1>            T=MyStruct
> 1>        ]
> 1>d:\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(488): note: see reference to function template instantiation 'auto struct_pack::detail::get_sorted_compatible_version_numbers<T>(void)' being compiled
> 1>        with
> 1>        [
> 1>            T=MyStruct
> 1>        ]
> 1>d:\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(496): note: see reference to function template instantiation 'auto struct_pack::detail::get_sorted_and_uniqued_compatible_version_numbers<T>(void)' being compiled
> 1>        with
> 1>        [
> 1>            T=MyStruct
> 1>        ]
> 1>d:\yalantinglibs\include\ylt\struct_pack\unpacker.hpp(157): note: see reference to variable template 'const auto compatible_version_number<MyStruct>' being compiled
> 1>d:\yalantinglibs\include\ylt\struct_pack.hpp(282): note: see reference to function template instantiation 'struct_pack::errc struct_pack::detail::unpacker<struct_pack::detail::memory_reader,0>::deserialize<T,>(T &)' being compiled
> 1>        with
> 1>        [
> 1>            T=MyStruct
> 1>        ]
> 1>d:\yalantinglibs\include\ylt\struct_pack.hpp(286): note: see reference to function template instantiation 'struct_pack::errc struct_pack::detail::unpacker<struct_pack::detail::memory_reader,0>::deserialize<T,>(T &)' being compiled
> 1>        with
> 1>        [
> 1>            T=MyStruct
> 1>        ]
> 1>d:\yalantinglibs\include\ylt\struct_pack.hpp(403): note: see reference to function template instantiation 'struct_pack::errc struct_pack::deserialize_to<0,U,,View,void>(T &,const View &)' being compiled
> 1>        with
> 1>        [
> 1>            U=MyStruct,
> 1>            View=std::vector<char,std::allocator<char>>,
> 1>            T=MyStruct
> 1>        ]
> 1>d:\vs\source\repos\consoleapplication1\consoleapplication1\consoleapplication1.cpp(19): note: see reference to function template instantiation 'tl::expected<MyStruct,struct_pack::errc> struct_pack::deserialize<MyStruct,Buffer,void>(const View &)' being compiled
> 1>        with
> 1>        [
> 1>            Buffer=std::vector<char,std::allocator<char>>,
> 1>            View=std::vector<char,std::allocator<char>>
> 1>        ]
> 1>c:\program files\microsoft visual studio\2022\enterprise\vc\tools\msvc\14.16.27023\include\variant(390): error C2065: 'value': undeclared identifier
> 1>c:\program files\microsoft visual studio\2022\enterprise\vc\tools\msvc\14.16.27023\include\variant(390): error C2131: expression did not evaluate to a constant
> 1>c:\program files\microsoft visual studio\2022\enterprise\vc\tools\msvc\14.16.27023\include\variant(390): note: a non-constant (sub-)expression was encountered
> 1>c:\program files\microsoft visual studio\2022\enterprise\vc\tools\msvc\14.16.27023\include\variant(390): error C2027: use of undefined type 'std::variant_size<_Ty>'
> 1>        with
> 1>        [
> 1>            _Ty=unsigned int
> 1>        ]
> 1>c:\program files\microsoft visual studio\2022\enterprise\vc\tools\msvc\14.16.27023\include\variant(390): note: see declaration of 'std::variant_size<_Ty>'
> 1>        with
> 1>        [
> 1>            _Ty=unsigned int
> 1>        ]
> 1>d:\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(591): note: see reference to variable template 'const size_t variant_size_v<unsigned int>' being compiled
> 1>d:\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(516): note: see reference to function template instantiation 'size_t struct_pack::detail::calculate_compatible_version_size<unsigned int,T>(void)' being compiled
> 1>d:\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(532): note: see reference to function template instantiation 'size_t struct_pack::detail::calculate_compatible_version_size<subArgs,T,0>(std::integer_sequence<unsigned __int64,0>)' being compiled
> 1>d:\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(478): note: see reference to function template instantiation 'size_t struct_pack::detail::calculate_compatible_version_size<T,>(void)' being compiled
> 1>        with
> 1>        [
> 1>            T=MyStruct
> 1>        ]
> 1>d:\yalantinglibs\include\ylt\struct_pack\util.h(83): error C2338: not allow empty input!
> 1>d:\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(490): note: see reference to function template instantiation 'void struct_pack::detail::compile_time_unique<uint64_t,0,0>(const std::array<uint64_t,0> &,std::array<uint64_t,0> &)' being compiled
> 1>d:\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(478): note: see reference to class template instantiation 'std::array<uint64_t,0>' being compiled
> 1>d:\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(488): note: see reference to function template instantiation 'std::array<uint64_t,0> struct_pack::detail::get_sorted_compatible_version_numbers<T>(void)' being compiled
> 1>        with
> 1>        [
> 1>            T=MyStruct
> 1>        ]
> 1>d:\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(496): note: see reference to function template instantiation 'std::array<uint64_t,0> struct_pack::detail::get_sorted_and_uniqued_compatible_version_numbers<T>(void)' being compiled
> 1>        with
> 1>        [
> 1>            T=MyStruct
> 1>        ]
> 1>d:\yalantinglibs\include\ylt\struct_pack\type_calculate.hpp(496): error C2131: expression did not evaluate to a constant
> 1>d:\yalantinglibs\include\ylt\struct_pack\util.h(84): note: failure was caused by call of undefined function or one not declared 'constexpr'
> 1>d:\yalantinglibs\include\ylt\struct_pack\util.h(84): note: see usage of 'std::array<uint64_t,0>::operator []'
> 1>Done building project "ConsoleApplication1.vcxproj" -- FAILED.
> ```

Use get_variant_size instead of std::variant_size_v in line 591.

**Comment by poor-circle** [comment]
You can replace all `variant_size_v` by get_variant_size. But I'm afraid their still has other problem. We need fix a lots of code.

**Comment by poor-circle** [comment]
I'm afraid it's no a simple problem. Maybe I will fix it later when I have time.
