### ISSUE TITLE
where is writer_bytes_array

### ISSUE THREAD

**Issue by 982945902** [alibaba/yalantinglibs#536]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen

branch: main

i canot find the writer_bytes_array  code

![image](https://github.com/alibaba/yalantinglibs/assets/49055103/f76b0d9a-a2a1-46e1-971b-204286343508)

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by poor-circle** [comment]
https://github.com/search?q=repo%3Aalibaba%2Fyalantinglibs%20writer_bytes_array&type=code

**Comment by poor-circle** [comment]
😂，thanks for your report. It's a typo. I'll add more test for it.

**Comment by 982945902** [comment]
> 😂，thanks for your report. It's a typo. I'll add more test for it.

it`s okay，but looks like there's another problem. I'll sync it up later

**Comment by poor-circle** [comment]
The function struct_pack::read/struct_pack::write/struct_pack::get_needed_size, which is designed for help user to serialize/deserialize the user-defined type. However, the document of those functions is miss, and it‘s not perfect and needs to be refactored and use the same code as the internal implementation. 
I will improve it later.

**Comment by poor-circle** [comment]
For now, I will just make a simple bugfix.
