### ISSUE TITLE
conn_id

### ISSUE THREAD

**Issue by kcjkcj3054** [alibaba/yalantinglibs#541]
Hello, get_connect_id was confirmed as a unique id in coro_rpc_client, what I want to check is the conn_id in coro_rpc_server.hpp.

According to the contributors, coro is stateless, but if the conn_id does not change in the client-server connection, it can be confirmed as stateful rather than stateless. Can I try modifying the conn_id?

What part of coro_rpc_server.hpp can I call by entering connec_id?

**Comment by poor-circle** [comment]
context<T>::get_connect_id will return the conn_id

**Comment by kcjkcj3054** [comment]
![image](https://github.com/alibaba/yalantinglibs/assets/147482125/07429af2-4bf3-463d-9b40-787977902c40)
If you look at the output screen above, you can see that the connection was not disconnected after connecting between the client and the server. I tested it for about 7 minutes. If this is the case, wouldn't it be considered stateful????

Please tell me the basis for being stateless
