### ISSUE TITLE
libprotoc

### ISSUE THREAD

**Issue by kcjkcj3054** [alibaba/yalantinglibs#547]
Currently, when I type protoc --version in cmd, libprotoc is output, but when I try to build it using cmake gui, INFOstruct_pb is skipped. To build struct_pb protoc plugin, you must install libprotoc first!!!
see https://alibaba.github.io/yalantinglibs/en/struct_pb/struct_pb_generating_your_struct.html
INFOto build struct_pb conformance test, you must install libprotoc first!!! This happens and I wonder why

**Comment by poor-circle** [comment]
I afraid struct_pb can't compatible with windows now.

**Comment by kcjkcj3054** [comment]
Is there a way to check?

**Comment by poor-circle** [comment]
The info means that find_package(Protobuf) is failed.

**Comment by kcjkcj3054** [comment]
That works if you use cmake, but can't you see the list supported by the protobuf plugin?

I asked a question because I didn't know much about the protobuf plugin. Thank you as always.

**Comment by kcjkcj3054** [comment]
So can you write in the documentation that struct_pb is not compatible with windows? Is it possible to find these parts as well?? I was additionally curious about this

**Comment by poor-circle** [comment]
> So can you write in the documentation that struct_pb is not compatible with windows? Is it possible to find these parts as well?? I was additionally curious about this
> 
> And in cmakelist.txt find_package(Protobuf QUIET) It says protobuf but not struct_pb. Does this mean that struct_pb is not compatible? In cmakelist, if an if condition passes, but if an issue occurs inside the content, can it fall to else? I was curious because it wasn't like that in regular code.

I mean, cmake build system can't found the libprotoc in your system.

**Comment by PikachuHyA** [comment]
> And in cmakelist.txt find_package(Protobuf QUIET)
> It says protobuf but not struct_pb. Does this mean that struct_pb is not compatible?

struct_pb plugin depends on libprotoc, so the check is required.
