### ISSUE TITLE
[struck_pack][md5constexpr][string_literal] 

### ISSUE THREAD

**Issue by sunflower-knight** [alibaba/yalantinglibs#553]
### Search before asking

- [x ] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen
```cpp
template <typename CharType, std::size_t Size>
string_literal(const CharType (&value)[Size])
-> string_literal<CharType, Size - 1>;
 ```
上面的代码是一个模板特化的构造函数，从字符数组中初始化 string_literal 对象，返回的对象类型是 string_literal<CharType, Size - 1>。这里 Size - 1 是为了排除 null 字符。

```cpp
    constexpr string_literal(const CharType (&value)[Size + 1]) : ar{} {
        for (size_t i = 0; i <= Size; ++i)
            ar[i] = value[i];
    }
```
而这个代码是从字符数组初始化 string_literal 对象，但这次的 Size + 1 是为了包括 null 字符，以便在循环中复制整个字符串。

At the firsttime we  use std::array to make string_literal , so we have `string_literal(const CharType (&value)[Size])
-> string_literal<CharType, Size - 1>;`

But now we use basic array , as the basic container in stringliteral

### Reproduction way
delete some code 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by poor-circle** [comment]
我明天看看吧，这里确实有点乱

**Comment by qicosmos** [comment]
你的问题是什么呢？@sunflower-knight

**Comment by sunflower-knight** [comment]
当从外界传入数组时 类型究竟是怎么推断的呢? 
   constexpr string_literal(const CharType (&value)[Size + 1]) : ar{} {
        for (size_t i = 0; i <= Size; ++i)
            ar[i] = value[i];
    }
    上面是根据构造函数推断的

    下面根据推到指引做类型推断
    template <typename CharType, std::size_t Size>
string_literal(const CharType (&value)[Size])
-> string_literal<CharType, Size - 1>;

size 的大小 在两种推断下 效果是一样的? 就是推断效果相同? 那么这两个代码的的功能就重复了

**Comment by sunflower-knight** [comment]
string_literal(const CharType (&value)[Size])
-> string_literal<CharType, Size - 1>; 
这段推导指引代码的存在 我记得是很久以前 在 实现stringliteral 的时候,底层使用了 Array 容器 ;

**Comment by poor-circle** [comment]
> size 的大小 在两种推断下 效果是一样的? 就是推断效果相同? 那么这两个代码的的功能就重复了

一个是构造函数的声明/实现，一个是deduction guide，两个不是重复的。
关于dedecution guide，请见：https://en.cppreference.com/w/cpp/language/class_template_argument_deduction

**Comment by poor-circle** [comment]
https://godbolt.org/z/93qPT75KK
The implicit deduction will failed. So we need add a manually dedecution guide.
