### ISSUE TITLE
question

### ISSUE THREAD

**Issue by kcjkcj3054** [alibaba/yalantinglibs#556]
Hi, by any chance the ding talk group disappeared. Did you unlock the room?

**Comment by qicosmos** [comment]
DingTalk group id: 645010455

**Comment by kcjkcj3054** [comment]
![image](https://github.com/alibaba/yalantinglibs/assets/147482125/0e96fcd3-9f8b-4d20-a4ab-ce2bd001ed0a)

**Comment by kcjkcj3054** [comment]
Why can't I see the group??
I have a question
What should I do when inserting content in json format in coro_http? json is in key:value format.

![image](https://github.com/alibaba/yalantinglibs/assets/147482125/c1d531df-b8d0-4601-b052-94e09be55d19)

**Comment by poor-circle** [comment]
dont search at groups, you should search it in the first tab.

**Comment by poor-circle** [comment]
> dont search at groups, you should search it in the first tab.

Or: public group

**Comment by kcjkcj3054** [comment]
![image](https://github.com/alibaba/yalantinglibs/assets/147482125/8d73b0d2-7456-4bba-bbb7-75633a1fc2e8)

**Comment by kcjkcj3054** [comment]
The group is not visible in the public group as well.

**Comment by kcjkcj3054** [comment]
In Postman, json is entered in the form {"name" : "asdf"}. How should I enter it in client.post?

**Comment by poor-circle** [comment]
> Reference in new

how you join it before?

**Comment by poor-circle** [comment]
> The group is not visible in the public group as well.

how you join it before?

**Comment by poor-circle** [comment]
> {"name" : "asdf"}

just set this string as the parameter of the client.post

**Comment by kcjkcj3054** [comment]
I did the same thing, but it doesn't work now, so I posted a question.

**Comment by poor-circle** [comment]
where is your history record?

**Comment by poor-circle** [comment]
> I did the same thing, but it doesn't work now, so I posted a question.
> 
> Is there an issue with dingtalk right now??

I can search it and there is no problem.

**Comment by kcjkcj3054** [comment]
I suddenly logged out of Dingtalk, and after logging back in, the group disappeared... I think it's an issue with my PC.

**Comment by kcjkcj3054** [comment]
![image](https://github.com/alibaba/yalantinglibs/assets/147482125/d632dbb4-5c92-4900-be1c-b2592e514df6)

I was curious because an issue occurred when I put it in general json format.


Also, from the perspective of the server that received the request, I want to see both the key and value.

**Comment by poor-circle** [comment]
https://qr.dingtalk.com/action/joingroup?code=v1,k1,y2Lc5Ni9wUDVBa592sWFBz5y75fLAD3Fth2/7XoDlYc=&_dt_no_comment=1&origin=11

**Comment by poor-circle** [comment]
https://github.com/alibaba/yalantinglibs/discussions

**Comment by poor-circle** [comment]
> https://github.com/alibaba/yalantinglibs/discussions

Please create you discussions here.

**Comment by kcjkcj3054** [comment]
Oh, I logged out again and logged back in and was able to find the group, so I sent another group request..! Sorry!
