### ISSUE TITLE
[struct_pack] [size_info][bug]

### ISSUE THREAD

**Issue by sunflower-knight** [alibaba/yalantinglibs#557]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen
In the file "size_info" in structpack 

  constexpr size_info operator+(const size_info &other) {
    return {this->total + other.total,
            this->size_cnt += other.size_cnt,
            (std::max)(this->max_size, other.max_size)};
  }

`this->size_cnt += other.size_cnt` may be a bug when you use operator '+', it will change change the info in this

**Comment by poor-circle** [comment]
Thanks! would you like submit a pr?
