### ISSUE TITLE
ylt\struct_pack\util.h中 定义的 #undef __has_feature 作用是什么，它会导致QT的__has_feature失效

### ISSUE THREAD

**Issue by RAVER0306** [alibaba/yalantinglibs#562]
![image](https://github.com/alibaba/yalantinglibs/assets/39723661/6955c53c-2d22-4c92-85ba-8ef2ef8f8dfc)

**Comment by poor-circle** [comment]
用处是取消前面定义的宏__has_feature,不过这里逻辑写的有点糙，看上去确实不太合适。修了一下
