### ISSUE TITLE
[feat] support vcpkg

### ISSUE THREAD

**Issue by icyfox168168** [alibaba/yalantinglibs#576]
### Search before asking

- [ ] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by poor-circle** [comment]
目前还没有支持vcpkg

**Comment by poor-circle** [comment]
vcpkg has support async_simple.

**Comment by icyfox168168** [comment]
非常好，希望尽快支持

**Comment by icyfox168168** [comment]
已经支持了，非常好
