### ISSUE TITLE
[struct_json]考虑为string解析为json时添加转义

### ISSUE THREAD

**Issue by Chessom** [alibaba/yalantinglibs#577]
目前的struct_json对string的内容没有检查，在字符串中含有单双引号等json语法字符时不会添加转义，导致解析to_json()产出的json时会解析失败。所以可否考虑为string对象添加对特殊字符的转义，或者添加一个重载？

**Comment by qicosmos** [comment]
谢谢报告，晚点回给出一个处理方法。

**Comment by Chessom** [comment]
谢谢你的工作，这个库很优雅实用！

**Comment by qicosmos** [comment]
@Chessom 
你可以验证一下这个pr吗？看看转义是不是解决了。默认是开启转义的，用户可以设置参数不启用转义。

 https://github.com/alibaba/yalantinglibs/pull/581

**Comment by Chessom** [comment]
@qicosmos 验证了几个样例，确实解决了，感谢付出。

**Comment by qicosmos** [comment]
感谢 @bbbgan 贡献的pr。
