### ISSUE TITLE
struct_pb适配的protobuf版本是什么

### ISSUE THREAD

**Issue by lnylgk** [alibaba/yalantinglibs#588]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### Anything else
我尝试了25.1和25.2在链接时都会出现下面的报错
ld: Undefined symbols:
  google::protobuf::io::Printer::PrintImpl(absl::lts_20240116::string_view, absl::lts_20240116::Span<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const>, google::protobuf::io::Printer::PrintOptions), referenced from:
      void google::protobuf::io::Printer::Print<absl::lts_20240116::flat_hash_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, absl::lts_20240116::container_internal::StringHash, absl::lts_20240116::container_internal::StringEq, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>>>(absl::lts_20240116::flat_hash_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, absl::lts_20240116::container_internal::StringHash, absl::lts_20240116::container_internal::StringEq, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&, absl::lts_20240116::string_view) in EnumFieldGenerator.cpp.o
      void google::protobuf::io::Printer::FormatInternal<std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>>>(absl::lts_20240116::Span<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const>, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&, absl::lts_20240116::string_view) in EnumFieldGenerator.cpp.o
      void google::protobuf::io::Printer::Print<absl::lts_20240116::flat_hash_map<absl::lts_20240116::string_view, absl::lts_20240116::string_view, absl::lts_20240116::container_internal::StringHash, absl::lts_20240116::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20240116::string_view const, absl::lts_20240116::string_view>>>>(absl::lts_20240116::flat_hash_map<absl::lts_20240116::string_view, absl::lts_20240116::string_view, absl::lts_20240116::container_internal::StringHash, absl::lts_20240116::container_internal::StringEq, std::__1::allocator<std::__1::pair<absl::lts_20240116::string_view const, absl::lts_20240116::string_view>>> const&, absl::lts_20240116::string_view) in EnumFieldGenerator.cpp.o
  google::protobuf::compiler::PluginMain(int, char**, google::protobuf::compiler::CodeGenerator const*), referenced from:
      _main in main.cpp.o
  google::protobuf::compiler::CodeGenerator::~CodeGenerator(), referenced from:
      struct_pb::compiler::StructGenerator::~StructGenerator() in StructGenerator.cpp.o
      struct_pb::compiler::StructGenerator::~StructGenerator() in StructGenerator.cpp.o
      _main in main.cpp.o
      _main in main.cpp.o
  google::protobuf::compiler::ParseGeneratorParameter(absl::lts_20240116::string_view, std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>>*), referenced from:
      struct_pb::compiler::StructGenerator::Generate(google::protobuf::FileDescriptor const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, google::protobuf::compiler::GeneratorContext*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*) const in StructGenerator.cpp.o
  google::protobuf::compiler::CodeGenerator::GenerateAll(std::__1::vector<google::protobuf::FileDescriptor const*, std::__1::allocator<google::protobuf::FileDescriptor const*>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, google::protobuf::compiler::GeneratorContext*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*) const, referenced from:
      vtable for struct_pb::compiler::StructGenerator in StructGenerator.cpp.o
  typeinfo for google::protobuf::compiler::CodeGenerator, referenced from:
      typeinfo for struct_pb::compiler::StructGenerator in StructGenerator.cpp.o

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by PikachuHyA** [comment]
这是protobuf在某个版本后依赖 absl，导致构建失败。
我之前适配时用的protobuf，还没有依赖过这个版本。
可以试下 protobuf 3.21这个版本

**Comment by lnylgk** [comment]
已经编译成功了，非常感谢
