### ISSUE TITLE
struct_pb ubuntu1804 gcc-9编译通过，但安装后 struct_pb.cmake 无法直接使用，且缺少 struct_pb_helper.cmake 文件

### ISSUE THREAD

**Issue by 171930433** [alibaba/yalantinglibs#594]
![image](https://github.com/alibaba/yalantinglibs/assets/32025811/52cfd48c-afbe-4008-b66b-e534bc90ec33)

默认分支，
安装后，无法使用target_protos_struct_pb 等函数生成 struct_pb.h

**Comment by PikachuHyA** [comment]
可以给个复现的demo代码，我测试一下吗？

**Comment by 171930433** [comment]
> 可以给个复现的demo代码，我测试一下吗？

你好，这个就是最新分支的源码，安装后使用，或者运行test时，全局搜索也没有找到  struct_pb_helper.cmake  这个文件。if("${yaLanTingLibs_SOURCE_DIR}" STREQUAL "${CMAKE_SOURCE_DIR}")
  # If this is a subproject in ylt
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/output/examples)
else() 走这个分支编译，运行example都是没问题的

**Comment by PikachuHyA** [comment]
的确有问题，我年后再修复吧

**Comment by PikachuHyA** [comment]
struct_pb重做了，新的版本详见文档

https://github.com/alibaba/yalantinglibs/blob/main/website/docs/zh/struct_pb/struct_pb_intro.md
