### ISSUE TITLE
Serialize/Deserialize a std::unique_ptr<base> instead of std::vector<std::unique_ptr<base>>.

### ISSUE THREAD

**Issue by WeaveAche** [alibaba/yalantinglibs#596]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen
In case of virtual base classes, struct_pack can serialize deserialize `std::vector<std::unique_ptr<base>>` but not `std::unique_ptr<base>`. Expect it to work in both cases?

### Reproduction way
```
#include <bits/stdc++.h>
#include "ylt/struct_pack.hpp"

struct base {
  virtual uint32_t get_struct_pack_id() const = 0;
  virtual std::string get_name() const = 0;
  int a = 1;
  virtual ~base(){};
};

inline std::string base::get_name() const { return std::to_string(a); }

struct derived1 : public base {
  virtual uint32_t get_struct_pack_id() const;
  virtual std::string get_name() const {
    return base::get_name() + std::to_string(b);
  }
  int b = 2;
};

STRUCT_PACK_REFL(derived1, a, b);
struct derived2 : public base {
  virtual uint32_t get_struct_pack_id() const;
  virtual std::string get_name() const { return base::get_name() + c; }
  std::string c = "Hello";
};

STRUCT_PACK_REFL(derived2, a, c);
struct derived3 : public base {
  virtual uint32_t get_struct_pack_id() const;
  virtual std::string get_name() const { return base::get_name() + d; }
  std::string d = "Oh no";
  static constexpr std::size_t struct_pack_id = 0;
};

STRUCT_PACK_REFL(derived3, a, d);

struct derived4 : public derived3 {
  virtual uint32_t get_struct_pack_id() const;
  virtual std::string get_name() const { return derived3::get_name() + e; }
  std::string e = "!";
};

STRUCT_PACK_REFL(derived4, a, d, e);

STRUCT_PACK_DERIVED_IMPL(base, derived1, derived2, derived3, derived4);

int main() {
    // This works
    std::vector<std::unique_ptr<base>> vec;
    vec.emplace_back(std::make_unique<derived4>());
    vec.emplace_back(std::make_unique<derived3>());
    vec.emplace_back(std::make_unique<derived2>());
    vec.emplace_back(std::make_unique<derived1>());
    auto buffer = struct_pack::serialize(vec);
    auto res = struct_pack::deserialize<std::vector<std::unique_ptr<base>>>(buffer);
    assert(res.has_value());

    // This fails
    std::unique_ptr<base> b = std::make_unique<derived4>();
    auto buffer2 = struct_pack::serialize(b);
    auto res2 = struct_pack::deserialize<std::unique_ptr<base>>(buffer2);
    assert(res2.has_value());
}
```

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by poor-circle** [comment]
`struct_pack::deserialize<std::vector<std::unique_ptr<base>>>` can only deserialize `std::vector<std::unique_ptr<base>>`

I think its expected behavior and struct_pack type check works well here.

you could use  `struct_pack::deserialize<std::unique_ptr<base>>` to deserialize `std::unique_ptr<base>`.

**Comment by WeaveAche** [comment]
> `struct_pack::deserialize<std::vector<std::unique_ptr<base>>>` can only deserialize `std::vector<std::unique_ptr<base>>`
> 
> I think it's an expected behavior and struct_pack type check works well here.
> 
> you could use `struct_pack::deserialize<std::unique_ptr<base>>` to deserialize `std::unique_ptr<base>`.

Sorry I had a typo in the previous example. Updated it.

**Comment by poor-circle** [comment]
ok i will check it later

**Comment by WeaveAche** [comment]
any updates?

**Comment by poor-circle** [comment]
> any updates?

Sorry but I'm in vacation, I will check it later.

**Comment by WeaveAche** [comment]
> > any updates?
> 
> Sorry but I'm in vacation, I will check it later.

No problem. Happy lunar new year.

**Comment by poor-circle** [comment]
Ok, I found the problem. 
https://github.com/alibaba/yalantinglibs/blob/1b5f5199d620f21183bff34935a2fb191ae326d3/include/ylt/struct_pack/calculate_size.hpp#L421
This line try to optimize the calculate of buffer size. however, we can't make sure if there has container when structure has a base class pointer. If there has a base class pointer, we should disable this optimization.

**Comment by poor-circle** [comment]
You can try to pull the code and check if problem fixed.
