### ISSUE TITLE
call coro_rpc function return bool crossplatform failed

### ISSUE THREAD

**Issue by yangxingpping** [alibaba/yalantinglibs#607]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### Anything else
<img width="1051" alt="bug描述" src="https://github.com/alibaba/yalantinglibs/assets/2830738/217aa558-5e92-4e29-b089-1aa917c97217">

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by poor-circle** [comment]
Fixed in #608
