### ISSUE TITLE
[feature][struct_json] support user-defined type

### ISSUE THREAD

**Issue by 171930433** [alibaba/yalantinglibs#616]
demo code如下:
```
#include <eigen3/Eigen/Dense>

struct person {
  std::string name;
  int age;
  Eigen::Vector3d pos;
};

REFLECTION(person, name, age, pos);

int main() {
  person p{"tom", 20};
  std::string str;

  // struct to json
  struct_json::to_json(p, str);
  std::cout << str << "\n";

  person p1;
  // json to struct
  struct_json::from_json(p1, str);
  assert(p == p1);
}
```

无法编译通过,在增加了 (目前看只有在Eigen命名空间下才能查询到):
```
namespace Eigen
{
template <typename Stream>
IGUANA_INLINE void render_json_value(Stream &ss, Eigen::Vector3d const& val) {
  std::stringstream ss2;
  ss2 << "[" << val[0] <<"," << val[1] <<"," <<val[2] <<"]";
  ss.append(ss2.str());
}
}
```

to_json函数可以编译通过, from_json编译提示缺少
```
template<typename It>
inline void parse_item(Eigen::Vector3d &value, It&& it, It&& end) {  },
``` 
但是放在哪里都没办法编译通过. 除非修改 iguanan/json_reader.hpp,放到这里库头文件里才行

问题: 在不修改iguanan库文件的情况下, 这些第三方库的复杂类型(Eigen::Matrix比较复杂,但是数值计算却比普通数组方便很多),如何自定义to_json,from_json. 例如 Eigen::Vector3d pos; 就当做double [3] 去自定义to_json,from_json

**Comment by qicosmos** [comment]
谢谢报告，晚点看一下。

**Comment by poor-circle** [comment]
我理解，其实就是如何支持自定义类型。
序列化和反序列化都应该支持ADL查找，找到用户自定义的函数。

**Comment by 171930433** [comment]
> 我理解，其实就是如何支持自定义类型。 序列化和反序列化都应该支持ADL查找，找到用户自定义的函数。

是的，https://github.com/alibaba/yalantinglibs/pull/619 看起来没有完全通过，请问我在那里可以获得修改过的代码

**Comment by poor-circle** [comment]
> > 我理解，其实就是如何支持自定义类型。 序列化和反序列化都应该支持ADL查找，找到用户自定义的函数。
> 
> 是的，#619 看起来没有完全通过，请问我在那里可以获得修改过的代码

今天会合入主线

**Comment by poor-circle** [comment]
> ADL查找

已合入主线，你可以试试看

**Comment by 171930433** [comment]
> > > 我理解，其实就是如何支持自定义类型。 序列化和反序列化都应该支持ADL查找，找到用户自定义的函数。
> > 
> > 
> > 是的，#619 看起来没有完全通过，请问我在那里可以获得修改过的代码
> 
> 拉下最新代码，你可以试下怎么样

已测试，可以正常使用 👍
