### ISSUE TITLE
[coro_rpc] Why the conn id is private

### ISSUE THREAD

**Issue by adjfangjiawei** [alibaba/yalantinglibs#622]
![QQ截图20240312130444](https://github.com/alibaba/yalantinglibs/assets/22865562/221b568d-a944-49f8-8a91-131d40d3e861)
![QQ截图20240312130501](https://github.com/alibaba/yalantinglibs/assets/22865562/eb607717-bd58-47a7-9e31-a47a1ab2245b)

**Comment by poor-circle** [comment]
you can visit it by member function `get_connection_id()`
