### ISSUE TITLE
std::wstring causes random crashes

### ISSUE THREAD

**Issue by romanholidaypancakes** [alibaba/yalantinglibs#630]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen

This happens on windows and randomly, parsing crashes on deserialization

### Reproduction way
-  [vs2022 c++ language property settings](https://learn.microsoft.com/en-us/cpp/build/reference/zc-wchar-t-wchar-t-is-native-type?view=msvc-170&f1url=%3FappId%3DDev17IDEF1%26l%3DEN-US%26k%3Dk(VC.Project.VCCLCompilerTool.TreatWChar_tAsBuiltInType)%26rd%3Dtrue)

![image](https://github.com/alibaba/yalantinglibs/assets/51652878/f1979681-dffc-449b-9b87-c308644cb7f2)

- sample code
NOTE: This is a random crash
```
struct MyStruct1 {
    struct MyStruct2 {
        std::map<std::wstring, unsigned> files;
    } s2;
};

int main() {
    auto s1                       = std::make_unique<MyStruct1>();
    s1->s2.files[L"c:\\12345678"] = 1;
    auto se1                      = struct_pack::serialize(s1);
    struct_pack::deserialize<MyStruct1>(se1);
}

```

- Crash at  https://github.com/alibaba/yalantinglibs/blob/a2b65ab6897506d42eb24184c8110802f0a46c6f/include/ylt/struct_pack/util.h#L214

![image](https://github.com/alibaba/yalantinglibs/assets/51652878/7ac543ff-5386-46f7-82a4-8e4adbbf4ab9)

![image](https://github.com/alibaba/yalantinglibs/assets/51652878/2a2b3817-0874-4183-8041-37fbda6fbde3)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by poor-circle** [comment]
it seems msvc is too smarter.

**Comment by poor-circle** [comment]
> it seems msvc is too smarter.

i will try to work it around later. the msvc is too sensetive here. i will use memset to instead of it.

**Comment by poor-circle** [comment]
Can you try to pull the code in #631 and check if the problem fixed?

**Comment by poor-circle** [comment]
> > Could you try to pull the code in #631 and check if the problem fixed?
> 
> It looks like making sure to truncate the last string at 0. If it is std::wstring, are you sure sz doesn't need to use `sz * 2` in this case?
> 
> And wstring(wchat*) should end with `00 00`

dont need, the size() return type is wchar* not char*.

**Comment by poor-circle** [comment]
Updated.

**Comment by poor-circle** [comment]
> > Could you try to pull the code in #631 and check if the problem fixed?
> 
> It looks like making sure to truncate the last string at 0. If it is std::wstring, are you sure sz doesn't need to use `sz * 2` in this case?
> 
> And wstring(wchat*) should end with `00 00`
> 
> And as far as I know the size of (string(wstring)) doesn't contain the backslash 0, so it shouldn't or doesn't need to be actively zeroed out

Updated.

**Comment by poor-circle** [comment]
> > Could you try to pull the code in #631 and check if the problem fixed?
> 
> It looks like making sure to truncate the last string at 0. If it is std::wstring, are you sure sz doesn't need to use `sz * 2` in this case?
> 
> And wstring(wchat*) should end with `00 00`
> 
> And as far as I know the size of (string(wstring)) doesn't contain the backslash 0, so it shouldn't or doesn't need to be actively zeroed out

Could you check it again?

**Comment by poor-circle** [comment]
> @poor-circle
> 
> Assuming I have the data
> 
> ```
> std::wstring wstr = L"123";
> ```
> 
> The size of it (`wstr.size()->sz`) is `3` and the memory pointed to by (`raw_str.data())` is:
> 
> ```
> 31 00 32 00 33 00 ?? ??
> ```
> 
> So it is mandatory here
> 
> ```
> *(raw_str.data() + sz) = 0xaaaa;
> ```
> 
> `reserve` only retains the length of the original data. Is it really safe to modify data beyond the original size?
> 
> ```
> 31 00 32 00 33 00 aa aa
> ```
> 
> Maybe the address that happens to point to `aa` is inaccessible.

See [document](https://en.cppreference.com/w/cpp/string/basic_string):

> a pointer to s[0] can be passed to functions that expect a pointer to the first element of a null-terminated array(since C++11) of CharT.

**Comment by poor-circle** [comment]
struct_pack::detail::resize() is very hack but it avoid the init when resize, so that it's 2X faster than other libs when you try to serialize/deserialize a big string or serialize to a string.
