### ISSUE TITLE
[fea] If A inherits from B and both need dynamic reflection features, how to write the demo code

### ISSUE THREAD

**Issue by 171930433** [alibaba/yalantinglibs#695]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen

age_ is missing

![image](https://github.com/alibaba/yalantinglibs/assets/32025811/79cd6d38-e1da-4225-8147-d3d6af52e924)

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by 171930433** [comment]
请问这个问题有没有解决思路，或者可以讨论一下方案，我可以负责实现部分 @qicosmos @poor-circle

**Comment by qicosmos** [comment]
@bbbgan 你也来看一下问题，我要晚点才有时间看这个问题。

**Comment by qicosmos** [comment]
@171930433 
不支持这种写法，pb的proto定义也没有继承的语义，应该用包含而不是继承方式。

可以这样写：
```cpp
struct test_st : iguana::base_impl<test_st> {
  int id;
  std::string name;
};
REFLECTION(test_st, id, name);

struct derived_st : iguana::base_impl<derived_st> {
  int age;
  test_st t;
};
REFLECTION(derived_st, age, t);
```
