### ISSUE TITLE
XML 只有标签中有数据，但是value 没有数据，该如何提取出来？

### ISSUE THREAD

**Issue by NSkyCh** [alibaba/yalantinglibs#728]
xml 如下, 我要怎么将里面的 Ext 和 size 提取出来, iguana::xml_attr_t 需要添加类型，随意添加类型会 unclosed tag
```
    <?xml version="1.0" encoding="UTF-8"?>
    <FileAttrs>
    	<FileAttr Ext=".dwg|.ppt|.c" />
    	<FileAttr Size="100" />
    </FileAttrs>
```

**Comment by qicosmos** [comment]
空白的，没看到xml内容。

**Comment by NSkyCh** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<FileAttrs>
	<FileAttr Ext=".dwg|.ppt|.c" />
	<FileAttr Size="100" />
</FileAttrs>

**Comment by qicosmos** [comment]
把xml文本内容发出来吧。

**Comment by NSkyCh** [comment]
![1722233160833](https://github.com/user-attachments/assets/255d3954-c584-43ae-a098-ad941efb6c92)

**Comment by qicosmos** [comment]
这样写就可以了：

```cpp
std::string str = R"(
  <?xml version="1.0" encoding="UTF-8"?>
  <FileAttrs>
    <FileAttr Ext=".dwg|.ppt|.c" />
    <FileAttr Size="100" />
  </FileAttrs>
)";
FileAttrs attrs{};
iguana::from_xml(attrs, str);
CHECK(attrs.FileAttr[0].attr()["Ext"]==".dwg|.ppt|.c");
CHECK(attrs.FileAttr[1].attr()["Size"]=="100");
```

**Comment by NSkyCh** [comment]
谢谢你的解答，我再问一下，如果说那一段改成类似这样，节点中的内容 1111111111 可能有也没有，是未知，这种场景能够解析出来不。
```
<FileAttr Ext=".dwg|.ppt|.c">1111111111</FileAttr>
<FileAttr Size="100" />
```

**Comment by qicosmos** [comment]
这种情况目前还不支持，因为` />`这种是没有值的，需要用optional类型来表示，而`>1111</FileAttr> `的值是int类型，不同类型没法放到容器里的。后面也许可以看看有没有什么办法能兼容这种混合标签的写法。
