### ISSUE TITLE
centos7 + clang9 + c++17 + ylt2.6.0 编译不过呀，请问clang9下如何编译通过 

### ISSUE THREAD

**Issue by bolanbujing** [alibaba/yalantinglibs#735]
### Search before asking

- [ ] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by bolanbujing** [comment]
各个版本下的编译环境没有说明，编译的时候很费力

**Comment by poor-circle** [comment]
发下报错信息

**Comment by bolanbujing** [comment]
主要报错是 error: variables defined in a constexpr function must be initialized

**Comment by poor-circle** [comment]
ci上使用clang-10测试，对于clang-9，如果编译不过，请发下完整的编译报错信息，我看看能不能支持

**Comment by bolanbujing** [comment]
include/ylt/struct_pack/calculate_size.hpp:99:14: error: variables defined in a constexpr function must be initialized
        bool is_ok;
             ^
In file included from /data/workspace/deploy_dtfn_2.0/framework/parallelconsensus/src/proposer/proposer_msg.cpp:1:
In file included from /data/workspace/deploy_dtfn_2.0/deps/include/ylt/struct_pack.hpp:30:
/data/workspace/deploy_dtfn_2.0/deps/include/ylt/struct_pack/packer.hpp:99:18: error: variables defined in a constexpr function must be initialized
        uint16_t len16;
                 ^
/data/workspace/deploy_dtfn_2.0/deps/include/ylt/struct_pack/packer.hpp:172:18: error: variables defined in a constexpr function must be initialized
            bool is_ok;
                 ^
In file included from /data/workspace/deploy_dtfn_2.0/framework/parallelconsensus/src/proposer/proposer_msg.cpp:1:
In file included from /data/workspace/deploy_dtfn_2.0/deps/include/ylt/struct_pack.hpp:36:
/data/workspace/deploy_dtfn_2.0/deps/include/ylt/struct_pack/unpacker.hpp:634:20: error: variables defined in a constexpr function must be initialized
          uint32_t id;
                   ^
In file included from /data/workspace/deploy_dtfn_2.0/framework/parallelconsensus/src/pbft/pbft_msg.cpp:3:
In file included from /data/workspace/deploy_dtfn_2.0/deps/include/ylt/struct_pack.hpp:24:
/data/workspace/deploy_dtfn_2.0/deps/include/ylt/struct_pack/calculate_size.hpp:99:14: error: variables defined in a constexpr function must be initialized
        bool is_ok;

**Comment by poor-circle** [comment]
ok，后面修下。如果没有别的问题的话，你可以选择升级编译器到clang-10以上，或者先给这几个代码初始化一下。

**Comment by poor-circle** [comment]
Fixed by #750
