### ISSUE TITLE
struct_pack 打包时，自动加入成员名字？

### ISSUE THREAD

**Issue by xhawk18** [alibaba/yalantinglibs#74]
自动获得struct成员的名字（无需用户添加声明成员名的代码），并放入打包的结果buffer中，有可能实现吗？

**Comment by poor-circle** [comment]
> 放入打包的结果buffer中，有可能实现吗？

指的是json格式吗？

**Comment by qicosmos** [comment]
> 自动获得struct成员的名字（无需用户添加声明成员名的代码），并放入打包的结果buffer中，有可能实现吗？

现在还不行，这个要在编译器层去做，或者等编译期反射进入标准了才可以，现在不得不用宏或者外部指定名称等方法才行。

**Comment by xhawk18** [comment]
> > 放入打包的结果buffer中，有可能实现吗？
> 
> 指的是json格式吗？

yes，是要json。struct_pack能反射出项目成员已经令人十分震惊，希望能再进一步

**Comment by poor-circle** [comment]
> > > 放入打包的结果buffer中，有可能实现吗？
> > 
> > 
> > 指的是json格式吗？
> 
> yes，是要json。struct_pack能反射出项目成员已经令人十分震惊，希望能再进一步

目前来看，想要拿到名字至少需要添加一个宏。反射成员的名字现在C++标准是做不到的。

**Comment by poor-circle** [comment]
> > > 放入打包的结果buffer中，有可能实现吗？
> > 
> > 
> > 指的是json格式吗？
> 
> yes，是要json。struct_pack能反射出项目成员已经令人十分震惊，希望能再进一步

json的支持已经在todolist里面了，不过还是需要用户添加一个宏

**Comment by qicosmos** [comment]
> 
json的支持已经提pr了：https://github.com/alibaba/yalantinglibs/pull/75
