### ISSUE TITLE
Does the `coro_rpc` only support request-response cycle?

### ISSUE THREAD

**Issue by GreyRaphael** [alibaba/yalantinglibs#760]
Great jobs!
 
I have tried the `coro_rpc` examples,  it seems that the interaction pattern of your Remote Procedure Call (RPC) model is a **request-response cycle**: the client sends **a request** to the server, and the server responds back with **a single response**.

Does the `coro_rpc` support the scenario where the client sends **only one request** to the server and then the server sends **many responses back** to the client, where the client maybe register a callback function,  everytime it receive a response the callback will be invoked.

**Comment by qicosmos** [comment]
coro_rpc not support such scenario now, will support pub/sub model later.

You can consider to use coro_http websocket to fit you requirement.

**Comment by GreyRaphael** [comment]
> coro_rpc not support such scenario now, will support pub/sub model later.
> 
> You can consider to use coro_http websocket to fit you requirement.

ok, thanks for your reply
