### ISSUE TITLE
Get member count error

### ISSUE THREAD

**Issue by PikachuHyA** [alibaba/yalantinglibs#84]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen

```cpp
class Foo {
 public:
  Foo(int foo): foo(foo) {

  }
 private:
  int foo;
};

struct Bar {
  Foo foo;
};
int main(){
  constexpr auto Count = struct_pack::detail::member_count<Bar>();
  std::cout << Count << std::endl;
}
```
Output: 0
Expected: 1

### Reproduction way

env: gcc 10.2.1

### Anything else

clang 13 has no such problem

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yanminhui** [comment]
maybe resolved by #304.

**Comment by poor-circle** [comment]
For this problem, we have two solution:
1. specify `struct_pack::members_count`
```cpp
template<>
constexpr std::size_t struct_pack::members_count<Bar> = 1;
```
2. use macro `STRUCT_PACK_REFL()`
see #382

**Comment by poor-circle** [comment]
Fixed by 382.
