### ISSUE TITLE
可以更新vcpkg版本不

### ISSUE THREAD

**Issue by icyfox168168** [alibaba/yalantinglibs#855]
### Search before asking

- [ ] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by qicosmos** [comment]
可以的，希望社区的同学帮助升级vcpkg版本，参考之前的PR。

**Comment by icyfox168168** [comment]
已经更新最新了
