### ISSUE TITLE
vcpkg版本缺少文件

### ISSUE THREAD

**Issue by icyfox168168** [alibaba/yalantinglibs#866]
standalone 目录

thirdparty 目录 

没有？

github打包源码是有的

**Comment by poor-circle** [comment]
因为vcpkg是包管理器，因此由vcpkg负责安装thirdparty第三方依赖。包括asio等。
standalone这个文件夹不存在，但是它内部的子文件夹会被安装。包括cinatra，iguana。
如果还有别的问题，你可以贴一下现在vcpkg目录下到底缺了什么

**Comment by icyfox168168** [comment]
能让vcpkg添加那些第三方不

#include "ylt/standalone/cinatra/picohttpparser.h"

vcpkg 就没picohttpparser这个库

我还有从github的源码找 本来挺方便，vcpkg，现在更不方便了

**Comment by poor-circle** [comment]
应该改变的是你的使用方式才对。
直接include "cinatra/xxx.h"

**Comment by poor-circle** [comment]
![IMG_20241222_053545](https://github.com/user-attachments/assets/b431233e-769a-4ef2-9e79-4f698265a3c1)

文档已经写的很清楚了，你之前应该是没加includepath，但是这样甚至编译都不应该通过。

**Comment by poor-circle** [comment]
> 这个文件有的啊，你只需要直接include "cinatra/xxx.h" 就行了，不要加那么多奇奇怪怪的前缀。

**Comment by poor-circle** [comment]
![IMG_20241222_053545](https://github.com/user-attachments/assets/1bcc9f74-120c-4fe4-af23-6d1e19e6beb0)
我假设你之前是直接把文件复制过去，没有走cmake安装。这种情况下，如果你没有按照图片里说的操作，把thirdpartyy和standalone加入includepath，那大量代码都是没法编译通过的。
