### ISSUE TITLE
struct_pack bug

### ISSUE THREAD

**Issue by manuel76413** [alibaba/yalantinglibs#867]
constexpr uint64_t unkval{ 999999llu };
#pragma pack(push, 1) 
struct runstat_s
{
  int currPhase{-1};                 
  uint64_t exist_count{ unkval };    
  uint64_t download_total_files{ unkval }; 
  uint64_t currBulkIndex{ unkval };  
  uint64_t currNcStepIndex{ unkval };
  usetstring fast_queue_set;         
  usetstring node_cache_set;         
  usetstring error_url_set;          
  usetstring error_nc_set;           
};

struct break_s
{
  int        top_bulk_level{ 9999 }; 
  usetstring top_bulk_set;           
  runstat_s  run_stat;               
};
#pragma pack(pop) 

break_s m_break;        //serialize-deserialize variable

#if defined(USE_STRUCT_PACK)
  svec<char> chars;
  struct_pack::serialize_to(chars, bn);
#else
  svec<uint8_t> bytes;
  alpaca::serialize(bn, bytes); 
#endif

//and deserialize
  bool br1 = false;
#if defined(USE_STRUCT_PACK) 
  struct_pack::err_code ec = struct_pack::deserialize_to(bn, (char*)chars.data(), chars.size());
  br1 = !ec;
#else
  std::error_code ec;
  bn = alpaca::deserialize<break_s>(bytes, ec);
  br1 = !ec;
#endif

in struct_pack report "no buffer space";
however  use alpaca, it success!

**Comment by poor-circle** [comment]
what is usetstring?

**Comment by poor-circle** [comment]
I guess the problem is caused by memory align. Please see document：[memory-alignment](https://alibaba.github.io/yalantinglibs/en/struct_pack/struct_pack_layout.html#memory-alignment)

you need add:
```
template<>
constexpr std::size_t struct_pack::pack_alignment<foo> = 1;
```

**Comment by manuel76413** [comment]
struct_pack::pack_alignment declared in which file?

**Comment by poor-circle** [comment]
> struct_pack::pack_alignment declared in which file?

You can declared in the same file of your struct
